package net.middledleeast.tamm.hotellibs.tektravel.hotelbookingapi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-06-26T14:07:39.499+02:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://TekTravel/HotelBookingApi", name = "IHotelService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IHotelService {

    @WebMethod(operationName = "HotelBookingDetail", action = "http://TekTravel/HotelBookingApi/HotelBookingDetail")
    @Action(input = "http://TekTravel/HotelBookingApi/HotelBookingDetail", output = "http://TekTravel/HotelBookingApi/IHotelService/HotelBookingDetailResponse")
    @WebResult(name = "HotelBookingDetailResponse", targetNamespace = "http://TekTravel/HotelBookingApi", partName = "parameters")
    public HotelBookingDetailResponse hotelBookingDetail(

            @WebParam(partName = "parameters", name = "HotelBookingDetailRequest", targetNamespace = "http://TekTravel/HotelBookingApi")
                    HotelBookingDetailRequest parameters
    );

    @WebMethod(operationName = "HotelBookingDetailBasedOnDate", action = "http://TekTravel/HotelBookingApi/HotelBookingDetailBasedOnDate")
    @Action(input = "http://TekTravel/HotelBookingApi/HotelBookingDetailBasedOnDate", output = "http://TekTravel/HotelBookingApi/IHotelService/HotelBookingDetailBasedOnDateResponse")
    @WebResult(name = "HotelBookingDetailBasedOnDateResponse", targetNamespace = "http://TekTravel/HotelBookingApi", partName = "parameters")
    public HotelBookingDetailBasedOnDateResponse hotelBookingDetailBasedOnDate(

            @WebParam(partName = "parameters", name = "HotelBookingDetailBasedOnDateRequest", targetNamespace = "http://TekTravel/HotelBookingApi")
                    HotelBookingDetailBasedOnDateRequest parameters
    );

    @WebMethod(operationName = "GiataHotelCodeList", action = "http://TekTravel/HotelBookingApi/GiataHotelCodes")
    @Action(input = "http://TekTravel/HotelBookingApi/GiataHotelCodes", output = "http://TekTravel/HotelBookingApi/IHotelService/GiataHotelCodeListResponse")
    @WebResult(name = "GiataHotelCodesResponse", targetNamespace = "http://TekTravel/HotelBookingApi", partName = "parameters")
    public GiataHotelCodesResponse giataHotelCodeList(

            @WebParam(partName = "parameters", name = "GiataHotelCodesRequest", targetNamespace = "http://TekTravel/HotelBookingApi")
                    GiataHotelCodesRequest parameters
    );

    @WebMethod(operationName = "HotelBook", action = "http://TekTravel/HotelBookingApi/HotelBook")
    @Action(input = "http://TekTravel/HotelBookingApi/HotelBook", output = "http://TekTravel/HotelBookingApi/IHotelService/HotelBookResponse")
    @WebResult(name = "HotelBookResponse", targetNamespace = "http://TekTravel/HotelBookingApi", partName = "parameters")
    public HotelBookResponse hotelBook(

            @WebParam(partName = "parameters", name = "HotelBookRequest", targetNamespace = "http://TekTravel/HotelBookingApi")
                    HotelBookRequest parameters
    );

    @WebMethod(operationName = "DestinationCityList", action = "http://TekTravel/HotelBookingApi/DestinationCityList")
    @Action(input = "http://TekTravel/HotelBookingApi/DestinationCityList", output = "http://TekTravel/HotelBookingApi/IHotelService/DestinationCityListResponse")
    @WebResult(name = "DestinationCityListResponse", targetNamespace = "http://TekTravel/HotelBookingApi", partName = "parameters")
    public DestinationCityListResponse destinationCityList(

            @WebParam(partName = "parameters", name = "DestinationCityListRequest", targetNamespace = "http://TekTravel/HotelBookingApi")
                    DestinationCityListRequest parameters
    );

    @WebMethod(operationName = "GenerateInvoice", action = "http://TekTravel/HotelBookingApi/GenerateInvoice")
    @Action(input = "http://TekTravel/HotelBookingApi/GenerateInvoice", output = "http://TekTravel/HotelBookingApi/IHotelService/GenerateInvoiceResponse")
    @WebResult(name = "GenerateInvoiceResponse", targetNamespace = "http://TekTravel/HotelBookingApi", partName = "parameters")
    public GenerateInvoiceResponse generateInvoice(

            @WebParam(partName = "parameters", name = "GenerateInvoiceRequest", targetNamespace = "http://TekTravel/HotelBookingApi")
                    GenerateInvoiceRequest parameters
    );

    @WebMethod(operationName = "AvailabilityAndPricing", action = "http://TekTravel/HotelBookingApi/AvailabilityAndPricing")
    @Action(input = "http://TekTravel/HotelBookingApi/AvailabilityAndPricing", output = "http://TekTravel/HotelBookingApi/IHotelService/AvailabilityAndPricingResponse")
    @WebResult(name = "AvailabilityAndPricingResponse", targetNamespace = "http://TekTravel/HotelBookingApi", partName = "parameters")
    public AvailabilityAndPricingResponse availabilityAndPricing(

            @WebParam(partName = "parameters", name = "AvailabilityAndPricingRequest", targetNamespace = "http://TekTravel/HotelBookingApi")
                    AvailabilityAndPricingRequest parameters
    );

    @WebMethod(operationName = "HotelCancellationPolicyForAllRooms", action = "http://TekTravel/HotelBookingApi/HotelCancellationPolicyForAllRooms")
    @Action(input = "http://TekTravel/HotelBookingApi/HotelCancellationPolicyForAllRooms", output = "http://TekTravel/HotelBookingApi/IHotelService/HotelCancellationPolicyForAllRoomsResponse")
    @WebResult(name = "HotelCancellationPolicyResponse", targetNamespace = "http://TekTravel/HotelBookingApi", partName = "parameters")
    public HotelCancellationPolicyResponse hotelCancellationPolicyForAllRooms(

            @WebParam(partName = "parameters", name = "HotelCancellationPolicyRequest", targetNamespace = "http://TekTravel/HotelBookingApi")
                    HotelCancellationPolicyRequest parameters
    );

    @WebMethod(operationName = "HotelCodeList", action = "http://TekTravel/HotelBookingApi/HotelCodes")
    @Action(input = "http://TekTravel/HotelBookingApi/HotelCodes", output = "http://TekTravel/HotelBookingApi/IHotelService/HotelCodeListResponse")
    @WebResult(name = "HotelCodesResponse", targetNamespace = "http://TekTravel/HotelBookingApi", partName = "parameters")
    public HotelCodesResponse hotelCodeList(

            @WebParam(partName = "parameters", name = "HotelCodesRequest", targetNamespace = "http://TekTravel/HotelBookingApi")
                    HotelCodesRequest parameters
    );

    @WebMethod(operationName = "HotelCancel", action = "http://TekTravel/HotelBookingApi/HotelCancel")
    @Action(input = "http://TekTravel/HotelBookingApi/HotelCancel", output = "http://TekTravel/HotelBookingApi/IHotelService/HotelCancelResponse")
    @WebResult(name = "HotelCancelResponse", targetNamespace = "http://TekTravel/HotelBookingApi", partName = "parameters")
    public HotelCancelResponse hotelCancel(

            @WebParam(partName = "parameters", name = "HotelCancelRequest", targetNamespace = "http://TekTravel/HotelBookingApi")
                    HotelCancelRequest parameters
    );

    @WebMethod(operationName = "HotelSearchWithRooms", action = "http://TekTravel/HotelBookingApi/HotelSearchWithRooms")
    @Action(input = "http://TekTravel/HotelBookingApi/HotelSearchWithRooms", output = "http://TekTravel/HotelBookingApi/IHotelService/HotelSearchWithRoomsResponse")
    @WebResult(name = "HotelSearchWithRoomsResponse", targetNamespace = "http://TekTravel/HotelBookingApi", partName = "parameters")
    public HotelSearchWithRoomsResponse hotelSearchWithRooms(

            @WebParam(partName = "parameters", name = "HotelSearchWithRoomsRequest", targetNamespace = "http://TekTravel/HotelBookingApi")
                    HotelSearchWithRoomsRequest parameters
    );

    @WebMethod(operationName = "HotelCancellationPolicy", action = "http://TekTravel/HotelBookingApi/HotelCancellationPolicy")
    @Action(input = "http://TekTravel/HotelBookingApi/HotelCancellationPolicy", output = "http://TekTravel/HotelBookingApi/IHotelService/HotelCancellationPolicyResponse")
    @WebResult(name = "HotelCancellationPolicyResponse", targetNamespace = "http://TekTravel/HotelBookingApi", partName = "parameters")
    public HotelCancellationPolicyResponse hotelCancellationPolicy(

            @WebParam(partName = "parameters", name = "HotelCancellationPolicyRequest", targetNamespace = "http://TekTravel/HotelBookingApi")
                    HotelCancellationPolicyRequest parameters
    );

    @WebMethod(operationName = "CityWiseNotification", action = "http://TekTravel/HotelBookingApi/CityWiseNotification")
    @Action(input = "http://TekTravel/HotelBookingApi/CityWiseNotification", output = "http://TekTravel/HotelBookingApi/IHotelService/CityWiseNotificationResponse")
    @WebResult(name = "CityWiseNotificationResponse", targetNamespace = "http://TekTravel/HotelBookingApi", partName = "parameters")
    public CityWiseNotificationResponse cityWiseNotification(

            @WebParam(partName = "parameters", name = "CityWiseNotificationRequest", targetNamespace = "http://TekTravel/HotelBookingApi")
                    CityWiseNotificationRequest parameters
    );

    @WebMethod(operationName = "TopDestinations", action = "http://TekTravel/HotelBookingApi/TopDestinations")
    @Action(input = "http://TekTravel/HotelBookingApi/TopDestinations", output = "http://TekTravel/HotelBookingApi/IHotelService/TopDestinationsResponse")
    @WebResult(name = "TopDestinationsResponse", targetNamespace = "http://TekTravel/HotelBookingApi", partName = "parameters")
    public TopDestinationsResponse topDestinations(

            @WebParam(partName = "parameters", name = "TopDestinationsRequest", targetNamespace = "http://TekTravel/HotelBookingApi")
                    TopDestinationsRequest parameters
    );

    @WebMethod(operationName = "Amendment", action = "http://TekTravel/HotelBookingApi/Amendment")
    @Action(input = "http://TekTravel/HotelBookingApi/Amendment", output = "http://TekTravel/HotelBookingApi/IHotelService/AmendmentResponse")
    @WebResult(name = "AmendmentResponse", targetNamespace = "http://TekTravel/HotelBookingApi", partName = "parameters")
    public AmendmentResponse amendment(

            @WebParam(partName = "parameters", name = "AmendmentRequest", targetNamespace = "http://TekTravel/HotelBookingApi")
                    AmendmentRequest parameters
    );

    @WebMethod(operationName = "CountryList", action = "http://TekTravel/HotelBookingApi/CountryList")
    @Action(input = "http://TekTravel/HotelBookingApi/CountryList", output = "http://TekTravel/HotelBookingApi/IHotelService/CountryListResponse")
    @WebResult(name = "CountryListResponse", targetNamespace = "http://TekTravel/HotelBookingApi", partName = "parameters")
    public CountryListResponse countryList(

            @WebParam(partName = "parameters", name = "CountryListRequest", targetNamespace = "http://TekTravel/HotelBookingApi")
                    CountryListRequest parameters
    );

    @WebMethod(operationName = "TagInfo", action = "http://TekTravel/HotelBookingApi/TagInfos")
    @Action(input = "http://TekTravel/HotelBookingApi/TagInfos", output = "http://TekTravel/HotelBookingApi/IHotelService/TagInfoResponse")
    @WebResult(name = "TagInfoResponse", targetNamespace = "http://TekTravel/HotelBookingApi", partName = "parameters")
    public TagInfoResponse tagInfo(

            @WebParam(partName = "parameters", name = "TagInfoRequest", targetNamespace = "http://TekTravel/HotelBookingApi")
                    TagInfoRequest parameters
    );

    @WebMethod(operationName = "HotelDetails", action = "http://TekTravel/HotelBookingApi/HotelDetails")
    @Action(input = "http://TekTravel/HotelBookingApi/HotelDetails", output = "http://TekTravel/HotelBookingApi/IHotelService/HotelDetailsResponse")
    @WebResult(name = "HotelDetailsResponse", targetNamespace = "http://TekTravel/HotelBookingApi", partName = "parameters")
    public HotelDetailsResponse hotelDetails(

            @WebParam(partName = "parameters", name = "HotelDetailsRequest", targetNamespace = "http://TekTravel/HotelBookingApi")
                    HotelDetailsRequest parameters
    );

    @WebMethod(operationName = "AvailableHotelRooms", action = "http://TekTravel/HotelBookingApi/AvailableHotelRooms")
    @Action(input = "http://TekTravel/HotelBookingApi/AvailableHotelRooms", output = "http://TekTravel/HotelBookingApi/IHotelService/AvailableHotelRoomsResponse")
    @WebResult(name = "HotelRoomAvailabilityResponse", targetNamespace = "http://TekTravel/HotelBookingApi", partName = "parameters")
    public HotelRoomAvailabilityResponse availableHotelRooms(

            @WebParam(partName = "parameters", name = "HotelRoomAvailabilityRequest", targetNamespace = "http://TekTravel/HotelBookingApi")
                    HotelRoomAvailabilityRequest parameters
    );

    @WebMethod(operationName = "HotelSearch", action = "http://TekTravel/HotelBookingApi/HotelSearch")
    @Action(input = "http://TekTravel/HotelBookingApi/HotelSearch", output = "http://TekTravel/HotelBookingApi/IHotelService/HotelSearchResponse")
    @WebResult(name = "HotelSearchResponse", targetNamespace = "http://TekTravel/HotelBookingApi", partName = "parameters")
    public HotelSearchResponse hotelSearch(

            @WebParam(partName = "parameters", name = "HotelSearchRequest", targetNamespace = "http://TekTravel/HotelBookingApi")
                    HotelSearchRequest parameters
    );
}
