package com.Tamm.Hotels.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.5.5
//
// Created by Quasar Development 
//
//---------------------------------------------------


import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class AddressInfo extends AttributeContainer implements KvmSerializable {


    public String AddressLine1;

    public String AddressLine2;

    public String CountryCode;

    public String AreaCode;

    public String PhoneNo;

    public String Email;

    public String City;

    public String State;

    public String Country;

    public String ZipCode;
    private transient java.lang.Object __source;


    public void loadFromSoap(java.lang.Object paramObj, ExtendedSoapSerializationEnvelope __envelope) {
        if (paramObj == null)
            return;
        AttributeContainer inObj = (AttributeContainer) paramObj;
        __source = inObj;
        if (inObj instanceof SoapObject) {
            SoapObject soapObject = (SoapObject) inObj;
            int size = soapObject.getPropertyCount();
            for (int i0 = 0; i0 < size; i0++) {
                PropertyInfo info = soapObject.getPropertyInfo(i0);
                if (!loadProperty(info, soapObject, __envelope)) {
                }
            }
        }

    }


    protected boolean loadProperty(PropertyInfo info, SoapObject soapObject, ExtendedSoapSerializationEnvelope __envelope) {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("AddressLine1")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.AddressLine1 = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.AddressLine1 = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("AddressLine2")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.AddressLine2 = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.AddressLine2 = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("CountryCode")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.CountryCode = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.CountryCode = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("AreaCode")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.AreaCode = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.AreaCode = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("PhoneNo")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.PhoneNo = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.PhoneNo = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("Email")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.Email = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.Email = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("City")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.City = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.City = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("State")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.State = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.State = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("Country")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.Country = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.Country = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("ZipCode")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.ZipCode = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.ZipCode = (String) obj;
                }
            }
            return true;
        }
        return false;
    }

    public java.lang.Object getOriginalXmlSource() {
        return __source;
    }


    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if (propertyIndex == 0) {
            return this.AddressLine1 != null ? this.AddressLine1 : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 1) {
            return this.AddressLine2 != null ? this.AddressLine2 : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 2) {
            return this.CountryCode != null ? this.CountryCode : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 3) {
            return this.AreaCode != null ? this.AreaCode : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 4) {
            return this.PhoneNo != null ? this.PhoneNo : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 5) {
            return this.Email != null ? this.Email : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 6) {
            return this.City != null ? this.City : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 7) {
            return this.State != null ? this.State : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 8) {
            return this.Country != null ? this.Country : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 9) {
            return this.ZipCode != null ? this.ZipCode : SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 10;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        if (propertyIndex == 0) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "AddressLine1";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 1) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "AddressLine2";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 2) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CountryCode";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 3) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "AreaCode";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 4) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "PhoneNo";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 5) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Email";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 6) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "City";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 7) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "State";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 8) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Country";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 9) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ZipCode";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1) {
    }


}

