package com.Tamm.Hotels.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.5.5
//
// Created by Quasar Development 
//
//---------------------------------------------------


import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.AttributeInfo;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class AgencyDetails extends AttributeContainer implements KvmSerializable {


    public String Name;

    public String AddressLine1;

    public String AddressLine2;

    public String Email;

    public String Phone;

    public String Fax;

    public String City;

    public String PIN;

    public String OfficeId;

    public String BookingMemberName;

    public String AgencyReference;
    private transient java.lang.Object __source;


    public void loadFromSoap(java.lang.Object paramObj, ExtendedSoapSerializationEnvelope __envelope) {
        if (paramObj == null)
            return;
        AttributeContainer inObj = (AttributeContainer) paramObj;
        __source = inObj;
        if (inObj instanceof SoapObject) {
            SoapObject soapObject = (SoapObject) inObj;
            int size = soapObject.getPropertyCount();
            for (int i0 = 0; i0 < size; i0++) {
                PropertyInfo info = soapObject.getPropertyInfo(i0);
                if (!loadProperty(info, soapObject, __envelope)) {
                }
            }
        }
        if (inObj.hasAttribute("AgencyReference")) {
            java.lang.Object j = inObj.getAttribute("AgencyReference");
            if (j != null) {
                AgencyReference = j.toString();
            }
        }

    }


    protected boolean loadProperty(PropertyInfo info, SoapObject soapObject, ExtendedSoapSerializationEnvelope __envelope) {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("Name")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.Name = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.Name = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("AddressLine1")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.AddressLine1 = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.AddressLine1 = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("AddressLine2")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.AddressLine2 = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.AddressLine2 = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("Email")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.Email = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.Email = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("Phone")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.Phone = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.Phone = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("Fax")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.Fax = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.Fax = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("City")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.City = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.City = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("PIN")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.PIN = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.PIN = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("OfficeId")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.OfficeId = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.OfficeId = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("BookingMemberName")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.BookingMemberName = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.BookingMemberName = (String) obj;
                }
            }
            return true;
        }
        return false;
    }

    public java.lang.Object getOriginalXmlSource() {
        return __source;
    }


    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if (propertyIndex == 0) {
            return this.Name != null ? this.Name : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 1) {
            return this.AddressLine1 != null ? this.AddressLine1 : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 2) {
            return this.AddressLine2 != null ? this.AddressLine2 : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 3) {
            return this.Email != null ? this.Email : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 4) {
            return this.Phone != null ? this.Phone : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 5) {
            return this.Fax != null ? this.Fax : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 6) {
            return this.City != null ? this.City : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 7) {
            return this.PIN != null ? this.PIN : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 8) {
            return this.OfficeId != null ? this.OfficeId : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 9) {
            return this.BookingMemberName != null ? this.BookingMemberName : SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 10;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        if (propertyIndex == 0) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Name";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 1) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "AddressLine1";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 2) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "AddressLine2";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 3) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Email";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 4) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Phone";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 5) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Fax";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 6) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "City";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 7) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "PIN";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 8) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "OfficeId";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 9) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "BookingMemberName";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1) {
    }


    @Override
    public int getAttributeCount() {
        return 1;
    }

    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if (index == 0) {
            info.name = "AgencyReference";
            info.namespace = "";
            if (this.AgencyReference != null) {
                info.setValue(this.AgencyReference);
            }

        }
    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }
}

