package com.Tamm.Hotels.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.6.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class AmendmentResponse extends AttributeContainer implements KvmSerializable {

    
    public ResponseStatus Status;

    public Enums.RequestStatus RequestStatus = Enums.RequestStatus.Unprocessed;
    
    public ApprovalInformation ApprovalInformation;

    public Integer BookingId = 0;
    
    public String NewConfirmatioNo;

    public String NewLastCancellationDate;

    public String AmendmentMessage;

    public AmendmentRequested AmendmentRequested;
    private transient java.lang.Object __source;


    public void loadFromSoap(java.lang.Object paramObj, ExtendedSoapSerializationEnvelope __envelope) {
        if (paramObj == null)
            return;
        AttributeContainer inObj = (AttributeContainer) paramObj;
        __source = inObj;
        if (inObj instanceof SoapObject) {
            SoapObject soapObject = (SoapObject) inObj;
            int size = soapObject.getPropertyCount();
            for (int i0 = 0; i0 < size; i0++) {
                PropertyInfo info = soapObject.getPropertyInfo(i0);
                if (!loadProperty(info, soapObject, __envelope)) {
                }
            } 
        }

    }


    protected boolean loadProperty(PropertyInfo info, SoapObject soapObject, ExtendedSoapSerializationEnvelope __envelope) {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("Status")) {
            if (obj != null) {
                java.lang.Object j = obj;
                this.Status = (ResponseStatus) __envelope.get(j, ResponseStatus.class, false);
            }
            return true;
        }
        if (info.name.equals("RequestStatus")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.RequestStatus = Enums.RequestStatus.fromString(j.toString());
                    }
                } else if (obj instanceof Enums.RequestStatus) {
                    this.RequestStatus = (Enums.RequestStatus) obj;
                }
            }
            return true;
        }
        if (info.name.equals("ApprovalInformation")) {
            if (obj != null) {
                java.lang.Object j = obj;
                this.ApprovalInformation = (ApprovalInformation) __envelope.get(j, ApprovalInformation.class, false);
            }
            return true;
        }
        if (info.name.equals("BookingId")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.BookingId = Integer.parseInt(j.toString());
                    }
                } else if (obj instanceof Integer) {
                    this.BookingId = (Integer) obj;
                }
            }
            return true;
        }
        if (info.name.equals("NewConfirmatioNo")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.NewConfirmatioNo = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.NewConfirmatioNo = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("NewLastCancellationDate")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.NewLastCancellationDate = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.NewLastCancellationDate = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("AmendmentMessage")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.AmendmentMessage = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.AmendmentMessage = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("AmendmentRequested")) {
            if (obj != null) {
                java.lang.Object j = obj;
                this.AmendmentRequested = (AmendmentRequested) __envelope.get(j, AmendmentRequested.class, false);
            }
            return true;
        }
        return false;
    }

    public java.lang.Object getOriginalXmlSource() {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if (propertyIndex == 0) {
            return this.Status != null ? this.Status : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 1) {
            return this.RequestStatus != null ? this.RequestStatus.toString() : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 2) {
            return this.ApprovalInformation != null ? this.ApprovalInformation : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 3) {
            return BookingId;
        }
        if (propertyIndex == 4) {
            return this.NewConfirmatioNo != null ? this.NewConfirmatioNo : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 5) {
            return this.NewLastCancellationDate != null ? this.NewLastCancellationDate : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 6) {
            return this.AmendmentMessage != null ? this.AmendmentMessage : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 7) {
            return this.AmendmentRequested != null ? this.AmendmentRequested : SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 8;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        if (propertyIndex == 0) {
            info.type = ResponseStatus.class;
            info.name = "Status";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 1) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "RequestStatus";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 2) {
            info.type = ApprovalInformation.class;
            info.name = "ApprovalInformation";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 3) {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "BookingId";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 4) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "NewConfirmatioNo";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 5) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "NewLastCancellationDate";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 6) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "AmendmentMessage";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 7) {
            info.type = AmendmentRequested.class;
            info.name = "AmendmentRequested";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1) {
    }


}

