package com.Tamm.Hotels.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.5.5
//
// Created by Quasar Development 
//
//---------------------------------------------------


import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class AOTNumbers extends AttributeContainer implements KvmSerializable {


    public String Country;

    public String Contact;

    public String IntlCall;

    public String DomesticCall;

    public String LocalCall;

    public String OfficeHours;

    public String Emergency;

    public String Language;
    private transient java.lang.Object __source;


    public void loadFromSoap(java.lang.Object paramObj, ExtendedSoapSerializationEnvelope __envelope) {
        if (paramObj == null)
            return;
        AttributeContainer inObj = (AttributeContainer) paramObj;
        __source = inObj;
        if (inObj instanceof SoapObject) {
            SoapObject soapObject = (SoapObject) inObj;
            int size = soapObject.getPropertyCount();
            for (int i0 = 0; i0 < size; i0++) {
                PropertyInfo info = soapObject.getPropertyInfo(i0);
                if (!loadProperty(info, soapObject, __envelope)) {
                }
            }
        }

    }


    protected boolean loadProperty(PropertyInfo info, SoapObject soapObject, ExtendedSoapSerializationEnvelope __envelope) {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("Country")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.Country = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.Country = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("Contact")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.Contact = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.Contact = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("IntlCall")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.IntlCall = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.IntlCall = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("DomesticCall")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.DomesticCall = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.DomesticCall = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("LocalCall")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.LocalCall = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.LocalCall = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("OfficeHours")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.OfficeHours = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.OfficeHours = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("Emergency")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.Emergency = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.Emergency = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("Language")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.Language = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.Language = (String) obj;
                }
            }
            return true;
        }
        return false;
    }

    public java.lang.Object getOriginalXmlSource() {
        return __source;
    }


    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if (propertyIndex == 0) {
            return this.Country != null ? this.Country : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 1) {
            return this.Contact != null ? this.Contact : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 2) {
            return this.IntlCall != null ? this.IntlCall : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 3) {
            return this.DomesticCall != null ? this.DomesticCall : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 4) {
            return this.LocalCall != null ? this.LocalCall : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 5) {
            return this.OfficeHours != null ? this.OfficeHours : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 6) {
            return this.Emergency != null ? this.Emergency : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 7) {
            return this.Language != null ? this.Language : SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 8;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        if (propertyIndex == 0) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Country";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 1) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Contact";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 2) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "IntlCall";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 3) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DomesticCall";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 4) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "LocalCall";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 5) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "OfficeHours";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 6) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Emergency";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 7) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Language";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1) {
    }


}

