package com.Tamm.Hotels.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.6.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.AttributeInfo;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.math.BigDecimal;
import java.util.Hashtable;

public class APIBookingDetail extends AttributeContainer implements KvmSerializable {

    
    public String HotelName;

    public Enums.HotelInfoHotelRating Rating = Enums.HotelInfoHotelRating.All;
    
    public String AddressLine1;

    public String AddressLine2;

    public String Map;

    public String City;

    public org.joda.time.LocalDate CheckInDate;

    public org.joda.time.LocalDate CheckOutDate;

    public org.joda.time.LocalDate BookingDate;

    public CancelPolicies HotelCancelPolicies;

    public String HotelPolicyDetails;

    public String FlightInfo;

    public String SpecialRequest;

    public ArrayOfRoomDetails Roomtype;

    public AmendmentDetails AmendmentDetails;

    public String Currency;

    public Integer NoOfRooms = 0;
    
    public AgencyDetails AgencyDetails;

    public AOTNumbers AOTNumbers;

    public Integer CityId = 0;
    
    public String TripName;

    public String TBOHotelCode;

    public BigDecimal CurrentCancellationCharges;

    public BigDecimal AppliedCancellationCharges;

    public Integer BookingId = 0;

    public Enums.RequestStatus AmendmentStatus = Enums.RequestStatus.Unprocessed;

    public Enums.APIHotelBookingStatus BookingStatus = Enums.APIHotelBookingStatus.Failed;

    public Boolean VoucherStatus = false;
    
    public String InvoiceNumber;

    public String SupplierReferenceNo;

    public String ConfirmationNo;

    public String HotelConfirmationNo;
    private transient java.lang.Object __source;


    public void loadFromSoap(java.lang.Object paramObj, ExtendedSoapSerializationEnvelope __envelope) {
        if (paramObj == null)
            return;
        AttributeContainer inObj = (AttributeContainer) paramObj;
        __source = inObj;
        if (inObj instanceof SoapObject) {
            SoapObject soapObject = (SoapObject) inObj;
            int size = soapObject.getPropertyCount();
            for (int i0 = 0; i0 < size; i0++) {
                PropertyInfo info = soapObject.getPropertyInfo(i0);
                if (!loadProperty(info, soapObject, __envelope)) {
                }
            } 
        }
        if (inObj.hasAttribute("BookingId")) {
            java.lang.Object j = inObj.getAttribute("BookingId");
            if (j != null) {
                BookingId = Integer.parseInt(j.toString());
            }
        }
        if (inObj.hasAttribute("AmendmentStatus")) {
            java.lang.Object j = inObj.getAttribute("AmendmentStatus");
            if (j != null) {
                AmendmentStatus = Enums.RequestStatus.fromString(j.toString());
            }
        }
        if (inObj.hasAttribute("BookingStatus")) {
            java.lang.Object j = inObj.getAttribute("BookingStatus");
            if (j != null) {
                BookingStatus = Enums.APIHotelBookingStatus.fromString(j.toString());
            }
        }
        if (inObj.hasAttribute("VoucherStatus")) {
            java.lang.Object j = inObj.getAttribute("VoucherStatus");
            if (j != null) {
                VoucherStatus = new Boolean(j.toString());
            }
        }
        if (inObj.hasAttribute("InvoiceNumber")) {
            java.lang.Object j = inObj.getAttribute("InvoiceNumber");
            if (j != null) {
                InvoiceNumber = j.toString();
            }
        }
        if (inObj.hasAttribute("SupplierReferenceNo")) {
            java.lang.Object j = inObj.getAttribute("SupplierReferenceNo");
            if (j != null) {
                SupplierReferenceNo = j.toString();
            }
        }
        if (inObj.hasAttribute("ConfirmationNo")) {
            java.lang.Object j = inObj.getAttribute("ConfirmationNo");
            if (j != null) {
                ConfirmationNo = j.toString();
            }
        }
        if (inObj.hasAttribute("HotelConfirmationNo")) {
            java.lang.Object j = inObj.getAttribute("HotelConfirmationNo");
            if (j != null) {
                HotelConfirmationNo = j.toString();
            }
        }

    }


    protected boolean loadProperty(PropertyInfo info, SoapObject soapObject, ExtendedSoapSerializationEnvelope __envelope) {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("HotelName")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.HotelName = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.HotelName = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("Rating")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.Rating = Enums.HotelInfoHotelRating.fromString(j.toString());
                    }
                } else if (obj instanceof Enums.HotelInfoHotelRating) {
                    this.Rating = (Enums.HotelInfoHotelRating) obj;
                }
            }
            return true;
        }
        if (info.name.equals("AddressLine1")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.AddressLine1 = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.AddressLine1 = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("AddressLine2")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.AddressLine2 = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.AddressLine2 = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("Map")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.Map = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.Map = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("City")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.City = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.City = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("CheckInDate")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.CheckInDate = Helper.ConvertFromWebServiceDate(j.toString());
                    }
                } else if (obj instanceof org.joda.time.LocalDate) {
                    this.CheckInDate = (org.joda.time.LocalDate) obj;
                }
            }
            return true;
        }
        if (info.name.equals("CheckOutDate")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.CheckOutDate = Helper.ConvertFromWebServiceDate(j.toString());
                    }
                } else if (obj instanceof org.joda.time.LocalDate) {
                    this.CheckOutDate = (org.joda.time.LocalDate) obj;
                }
            }
            return true;
        }
        if (info.name.equals("BookingDate")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.BookingDate = Helper.ConvertFromWebServiceDate(j.toString());
                    }
                } else if (obj instanceof org.joda.time.LocalDate) {
                    this.BookingDate = (org.joda.time.LocalDate) obj;
                }
            }
            return true;
        }
        if (info.name.equals("HotelCancelPolicies")) {
            if (obj != null) {
                java.lang.Object j = obj;
                this.HotelCancelPolicies = (CancelPolicies) __envelope.get(j, CancelPolicies.class, false);
            }
            return true;
        }
        if (info.name.equals("HotelPolicyDetails")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.HotelPolicyDetails = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.HotelPolicyDetails = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("FlightInfo")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.FlightInfo = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.FlightInfo = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("SpecialRequest")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.SpecialRequest = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.SpecialRequest = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("Roomtype")) {
            if (obj != null) {
                java.lang.Object j = obj;
                this.Roomtype = (ArrayOfRoomDetails) __envelope.get(j, ArrayOfRoomDetails.class, false);
            }
            return true;
        }
        if (info.name.equals("AmendmentDetails")) {
            if (obj != null) {
                java.lang.Object j = obj;
                this.AmendmentDetails = (AmendmentDetails) __envelope.get(j, AmendmentDetails.class, false);
            }
            return true;
        }
        if (info.name.equals("Currency")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.Currency = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.Currency = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("NoOfRooms")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.NoOfRooms = Integer.parseInt(j.toString());
                    }
                } else if (obj instanceof Integer) {
                    this.NoOfRooms = (Integer) obj;
                }
            }
            return true;
        }
        if (info.name.equals("AgencyDetails")) {
            if (obj != null) {
                java.lang.Object j = obj;
                this.AgencyDetails = (AgencyDetails) __envelope.get(j, AgencyDetails.class, false);
            }
            return true;
        }
        if (info.name.equals("AOTNumbers")) {
            if (obj != null) {
                java.lang.Object j = obj;
                this.AOTNumbers = (AOTNumbers) __envelope.get(j, AOTNumbers.class, false);
            }
            return true;
        }
        if (info.name.equals("CityId")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.CityId = Integer.parseInt(j.toString());
                    }
                } else if (obj instanceof Integer) {
                    this.CityId = (Integer) obj;
                }
            }
            return true;
        }
        if (info.name.equals("TripName")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.TripName = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.TripName = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("TBOHotelCode")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.TBOHotelCode = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.TBOHotelCode = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("CurrentCancellationCharges")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.CurrentCancellationCharges = new BigDecimal(j.toString());
                    }
                } else if (obj instanceof BigDecimal) {
                    this.CurrentCancellationCharges = (BigDecimal) obj;
                }
            }
            return true;
        }
        if (info.name.equals("AppliedCancellationCharges")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.AppliedCancellationCharges = new BigDecimal(j.toString());
                    }
                } else if (obj instanceof BigDecimal) {
                    this.AppliedCancellationCharges = (BigDecimal) obj;
                }
            }
            return true;
        }
        return false;
    }

    public java.lang.Object getOriginalXmlSource() {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if (propertyIndex == 0) {
            return this.HotelName != null ? this.HotelName : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 1) {
            return this.Rating != null ? this.Rating.toString() : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 2) {
            return this.AddressLine1 != null ? this.AddressLine1 : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 3) {
            return this.AddressLine2 != null ? this.AddressLine2 : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 4) {
            return this.Map != null ? this.Map : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 5) {
            return this.City != null ? this.City : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 6) {
            return this.CheckInDate != null ? this.CheckInDate.toString() : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 7) {
            return this.CheckOutDate != null ? this.CheckOutDate.toString() : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 8) {
            return this.BookingDate != null ? this.BookingDate.toString() : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 9) {
            return this.HotelCancelPolicies != null ? this.HotelCancelPolicies : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 10) {
            return this.HotelPolicyDetails != null ? this.HotelPolicyDetails : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 11) {
            return this.FlightInfo != null ? this.FlightInfo : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 12) {
            return this.SpecialRequest != null ? this.SpecialRequest : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 13) {
            return this.Roomtype != null ? this.Roomtype : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 14) {
            return this.AmendmentDetails != null ? this.AmendmentDetails : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 15) {
            return this.Currency != null ? this.Currency : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 16) {
            return NoOfRooms;
        }
        if (propertyIndex == 17) {
            return this.AgencyDetails != null ? this.AgencyDetails : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 18) {
            return this.AOTNumbers != null ? this.AOTNumbers : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 19) {
            return CityId;
        }
        if (propertyIndex == 20) {
            return this.TripName != null ? this.TripName : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 21) {
            return this.TBOHotelCode != null ? this.TBOHotelCode : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 22) {
            return this.CurrentCancellationCharges != null ? this.CurrentCancellationCharges.toString() : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 23) {
            return this.AppliedCancellationCharges != null ? this.AppliedCancellationCharges.toString() : SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 24;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        if (propertyIndex == 0) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "HotelName";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 1) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Rating";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 2) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "AddressLine1";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 3) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "AddressLine2";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 4) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Map";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 5) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "City";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 6) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CheckInDate";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 7) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CheckOutDate";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 8) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "BookingDate";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 9) {
            info.type = CancelPolicies.class;
            info.name = "HotelCancelPolicies";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 10) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "HotelPolicyDetails";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 11) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "FlightInfo";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 12) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SpecialRequest";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 13) {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "Roomtype";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 14) {
            info.type = AmendmentDetails.class;
            info.name = "AmendmentDetails";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 15) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Currency";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 16) {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "NoOfRooms";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 17) {
            info.type = AgencyDetails.class;
            info.name = "AgencyDetails";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 18) {
            info.type = AOTNumbers.class;
            info.name = "AOTNumbers";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 19) {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "CityId";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 20) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TripName";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 21) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TBOHotelCode";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 22) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CurrentCancellationCharges";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 23) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "AppliedCancellationCharges";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1) {
    }



    @Override
    public int getAttributeCount() {
        return 8;
    }

    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if (index == 0) {
            info.name = "BookingId";
            info.namespace = "";
            if (this.BookingId != null) {
                info.setValue(this.BookingId);
            }

        }
        if (index == 1) {
            info.name = "AmendmentStatus";
            info.namespace = "";
            if (this.AmendmentStatus != null) {
                info.setValue(this.AmendmentStatus);
            }

        }
        if (index == 2) {
            info.name = "BookingStatus";
            info.namespace = "";
            if (this.BookingStatus != null) {
                info.setValue(this.BookingStatus);
            }

        }
        if (index == 3) {
            info.name = "VoucherStatus";
            info.namespace = "";
            if (this.VoucherStatus != null) {
                info.setValue(this.VoucherStatus);
            }

        }
        if (index == 4) {
            info.name = "InvoiceNumber";
            info.namespace = "";
            if (this.InvoiceNumber != null) {
                info.setValue(this.InvoiceNumber);
            }

        }
        if (index == 5) {
            info.name = "SupplierReferenceNo";
            info.namespace = "";
            if (this.SupplierReferenceNo != null) {
                info.setValue(this.SupplierReferenceNo);
            }

        }
        if (index == 6) {
            info.name = "ConfirmationNo";
            info.namespace = "";
            if (this.ConfirmationNo != null) {
                info.setValue(this.ConfirmationNo);
            }

        }
        if (index == 7) {
            info.name = "HotelConfirmationNo";
            info.namespace = "";
            if (this.HotelConfirmationNo != null) {
                info.setValue(this.HotelConfirmationNo);
            }

        }
    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }    
}

