package com.Tamm.Hotels.wcf;


//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.6.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;
import org.kxml2.kdom.Element;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


public class BasicHttpBinding_IHotelService1 {
    public List<HeaderProperty> httpHeaders = new ArrayList<HeaderProperty>();
    String url = "https://api.tbotechnology.in/HotelAPI_V7/HotelService.svc/basic";

    int timeOut = 60000;

    public BasicHttpBinding_IHotelService1() {
    }
    public boolean enableLogging;
    public boolean createClassesForAny = false;

    IServiceEvents callback;

    public BasicHttpBinding_IHotelService1(IServiceEvents callback) {
        this.callback = callback;
    }

    public BasicHttpBinding_IHotelService1(IServiceEvents callback, String url) {
        this.callback = callback;
        this.url = url;
    }

    public BasicHttpBinding_IHotelService1(IServiceEvents callback, String url, int timeOut) {
        this.callback = callback;
        this.url = url;
        this.timeOut = timeOut;
    }

    protected org.ksoap2.transport.Transport createTransport() {
        try {
            java.net.URI uri = new java.net.URI(url);
            if (uri.getScheme().equalsIgnoreCase("https")) {
                int port = uri.getPort() > 0 ? uri.getPort() : 443;
                return new com.easywsdl.exksoap2.transport.AdvancedHttpsTransportSE(uri.getHost(), port, uri.getPath(), timeOut);
            } else {
                return new com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE(url, timeOut);
            }

        } catch (java.net.URISyntaxException e) {
        }
        return null;
    }

    protected ExtendedSoapSerializationEnvelope createEnvelope() {
        ExtendedSoapSerializationEnvelope envelope = new ExtendedSoapSerializationEnvelope(ExtendedSoapSerializationEnvelope.VER11);
        envelope.createClassesForAny = createClassesForAny;
        return envelope;
    }

    protected java.util.List sendRequest(String methodName, ExtendedSoapSerializationEnvelope envelope, org.ksoap2.transport.Transport transport, com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile profile) throws java.lang.Exception {
        if (transport instanceof com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE) {
            return ((com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE) transport).call(methodName, envelope, httpHeaders, null, profile);
        } else {
            return ((com.easywsdl.exksoap2.transport.AdvancedHttpsTransportSE) transport).call(methodName, envelope, httpHeaders, null, profile);
        }
    }

    java.lang.Object getResult(java.lang.Class destObj, java.lang.Object source, String resultName, ExtendedSoapSerializationEnvelope __envelope) throws java.lang.Exception {
        if (source == null) {
            return null;
        }
        if (source instanceof SoapPrimitive) {
            SoapPrimitive soap = (SoapPrimitive) source;
            if (soap.getName().equals(resultName)) {
                java.lang.Object instance = __envelope.get(source, destObj, false);
                return instance;
            }
        } else {
            SoapObject soap = (SoapObject) source;
            if (soap.hasProperty(resultName)) {
                java.lang.Object j = soap.getProperty(resultName);
                if (j == null) {
                    return null;
                }
                java.lang.Object instance = __envelope.get(j, destObj, false);
                return instance;
            } else if (soap.getName().equals(resultName)) {
                java.lang.Object instance = __envelope.get(source, destObj, false);
                return instance;
            }
        }

        return null;
    }

    public HotelSearchResponse HotelSearch(final org.joda.time.DateTime CheckInDate, final org.joda.time.DateTime CheckOutDate, final String CountryName, final String CityName, final Integer CityId, final Boolean IsNearBySearchAllowed, final Integer NoOfRooms, final String GuestNationality, final ArrayOfRoomGuest RoomGuests, final String PreferredCurrencyCode, final Integer ResultCount, final Filters Filters, final String IsRoomInfoRequired, final GeoCodes GeoCodes, final Integer ResponseTime, final AuthenticationData Credentials) throws java.lang.Exception {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (HotelSearchResponse) execute(new IWcfMethod() {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                ArrayList<org.kxml2.kdom.Element> __headers = null;
                if (__envelope.headerOut == null) {
                    __headers = new ArrayList<org.kxml2.kdom.Element>();
                } else {
                    __headers = new ArrayList<org.kxml2.kdom.Element>(Arrays.asList(__envelope.headerOut));
                }
                __headers.add(Helper.convertToHeader(Credentials != null ? Credentials : SoapPrimitive.NullNilElement, "http://TekTravel/HotelBookingApi", "Credentials"));
                __envelope.headerOut = __headers.toArray(new Element[__headers.size()]);
                __envelope.addMapping("http://TekTravel/HotelBookingApi", "RoomGuests", new ArrayOfRoomGuest().getClass());
                __envelope.addMapping("http://TekTravel/HotelBookingApi", "Filters", new Filters().getClass());
                __envelope.addMapping("http://TekTravel/HotelBookingApi", "GeoCodes", new GeoCodes().getClass());
                SoapObject __soapReq = new SoapObject("http://TekTravel/HotelBookingApi", "HotelSearchRequest");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "CheckInDate";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(CheckInDate != null ? CheckInDate.toString() : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "CheckOutDate";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(CheckOutDate != null ? CheckOutDate.toString() : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "CountryName";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(CountryName != null ? CountryName : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "CityName";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(CityName != null ? CityName : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "CityId";
                __info.type = PropertyInfo.INTEGER_CLASS;
                __info.setValue(CityId);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "IsNearBySearchAllowed";
                __info.type = PropertyInfo.BOOLEAN_CLASS;
                __info.setValue(IsNearBySearchAllowed);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "NoOfRooms";
                __info.type = PropertyInfo.INTEGER_CLASS;
                __info.setValue(NoOfRooms);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "GuestNationality";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(GuestNationality != null ? GuestNationality : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "RoomGuests";
                __info.type = PropertyInfo.VECTOR_CLASS;
                __info.setValue(RoomGuests != null ? RoomGuests : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "PreferredCurrencyCode";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(PreferredCurrencyCode != null ? PreferredCurrencyCode : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "ResultCount";
                __info.type = PropertyInfo.INTEGER_CLASS;
                __info.setValue(ResultCount);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "Filters";
                __info.type = Filters.class;
                __info.setValue(Filters != null ? Filters : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "IsRoomInfoRequired";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(IsRoomInfoRequired != null ? IsRoomInfoRequired : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "GeoCodes";
                __info.type = GeoCodes.class;
                __info.setValue(GeoCodes != null ? GeoCodes : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "ResponseTime";
                __info.type = PropertyInfo.INTEGER_CLASS;
                __info.setValue(ResponseTime);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                return getResult(HotelSearchResponse.class, __result, "HotelSearchResponse", __envelope);
            }
        }, "http://TekTravel/HotelBookingApi/HotelSearch", __profile);
    }

    public HotelSearchResponse HotelSearch1(final org.joda.time.DateTime CheckInDate, final org.joda.time.DateTime CheckOutDate, final Integer CityId, final Integer NoOfRooms, final ArrayOfRoomGuest RoomGuests, final String GuestNationality, final AuthenticationData Credentials) throws java.lang.Exception {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (HotelSearchResponse) execute(new IWcfMethod() {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                ArrayList<org.kxml2.kdom.Element> __headers = null;
                if (__envelope.headerOut == null) {
                    __headers = new ArrayList<org.kxml2.kdom.Element>();
                } else {
                    __headers = new ArrayList<org.kxml2.kdom.Element>(Arrays.asList(__envelope.headerOut));
                }
                __headers.add(Helper.convertToHeader(Credentials != null ? Credentials : SoapPrimitive.NullNilElement, "http://TekTravel/HotelBookingApi", "Credentials"));
                __envelope.headerOut = __headers.toArray(new Element[__headers.size()]);
                __envelope.addMapping("http://TekTravel/HotelBookingApi", "RoomGuests", new ArrayOfRoomGuest().getClass());
                __envelope.addMapping("http://TekTravel/HotelBookingApi", "Filters", new Filters().getClass());
                __envelope.addMapping("http://TekTravel/HotelBookingApi", "GeoCodes", new GeoCodes().getClass());
                SoapObject __soapReq = new SoapObject("http://TekTravel/HotelBookingApi", "HotelSearchRequest");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "CheckInDate";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(CheckInDate != null ? CheckInDate.toString() : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "CheckOutDate";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(CheckOutDate != null ? CheckOutDate.toString() : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "GuestNationality";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(GuestNationality != null ? GuestNationality : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "CityId";
                __info.type = PropertyInfo.INTEGER_CLASS;
                __info.setValue(CityId);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "NoOfRooms";
                __info.type = PropertyInfo.INTEGER_CLASS;
                __info.setValue(NoOfRooms);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "RoomGuests";
                __info.type = PropertyInfo.VECTOR_CLASS;
                __info.setValue(RoomGuests != null ? RoomGuests : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);

                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                return getResult(HotelSearchResponse.class, __result, "HotelSearchResponse", __envelope);
            }
        }, "http://TekTravel/HotelBookingApi/HotelSearch", __profile);
    }


    public android.os.AsyncTask<Void, Void, OperationResult<HotelSearchResponse>> HotelSearchAsync(final org.joda.time.DateTime CheckInDate, final org.joda.time.DateTime CheckOutDate, final String CountryName, final String CityName, final Integer CityId, final Boolean IsNearBySearchAllowed, final Integer NoOfRooms, final String GuestNationality, final ArrayOfRoomGuest RoomGuests, final String PreferredCurrencyCode, final Integer ResultCount, final Filters Filters, final String IsRoomInfoRequired, final GeoCodes GeoCodes, final Integer ResponseTime, final AuthenticationData Credentials) {
        return executeAsync(new Functions.IFunc<HotelSearchResponse>() {
            public HotelSearchResponse Func() throws java.lang.Exception {
                return HotelSearch(CheckInDate, CheckOutDate, CountryName, CityName, CityId, IsNearBySearchAllowed, NoOfRooms, GuestNationality, RoomGuests, PreferredCurrencyCode, ResultCount, Filters, IsRoomInfoRequired, GeoCodes, ResponseTime, Credentials);
            }
        }, "HotelSearch");
    }

    public HotelRoomAvailabilityResponse AvailableHotelRooms(final String SessionId, final Integer ResultIndex, final String HotelCode, final Integer ResponseTime, final Boolean IsCancellationPolicyRequired, final AuthenticationData Credentials) throws java.lang.Exception {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (HotelRoomAvailabilityResponse) execute(new IWcfMethod() {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                ArrayList<org.kxml2.kdom.Element> __headers = null;
                if (__envelope.headerOut == null) {
                    __headers = new ArrayList<org.kxml2.kdom.Element>();
                } else {
                    __headers = new ArrayList<org.kxml2.kdom.Element>(Arrays.asList(__envelope.headerOut));
                }
                __headers.add(Helper.convertToHeader(Credentials != null ? Credentials : SoapPrimitive.NullNilElement, "http://TekTravel/HotelBookingApi", "Credentials"));
                __envelope.headerOut = __headers.toArray(new Element[__headers.size()]);
                SoapObject __soapReq = new SoapObject("http://TekTravel/HotelBookingApi", "HotelRoomAvailabilityRequest");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "SessionId";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(SessionId != null ? SessionId : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "ResultIndex";
                __info.type = PropertyInfo.INTEGER_CLASS;
                __info.setValue(ResultIndex);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "HotelCode";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(HotelCode != null ? HotelCode : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "ResponseTime";
                __info.type = PropertyInfo.INTEGER_CLASS;
                __info.setValue(ResponseTime);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "IsCancellationPolicyRequired";
                __info.type = PropertyInfo.BOOLEAN_CLASS;
                __info.setValue(IsCancellationPolicyRequired);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                return getResult(HotelRoomAvailabilityResponse.class, __result, "HotelRoomAvailabilityResponse", __envelope);
            }
        }, "http://TekTravel/HotelBookingApi/AvailableHotelRooms", __profile);
    }

    public android.os.AsyncTask<Void, Void, OperationResult<HotelRoomAvailabilityResponse>> AvailableHotelRoomsAsync(final String SessionId, final Integer ResultIndex, final String HotelCode, final Integer ResponseTime, final Boolean IsCancellationPolicyRequired, final AuthenticationData Credentials) {
        return executeAsync(new Functions.IFunc<HotelRoomAvailabilityResponse>() {
            public HotelRoomAvailabilityResponse Func() throws java.lang.Exception {
                return AvailableHotelRooms(SessionId, ResultIndex, HotelCode, ResponseTime, IsCancellationPolicyRequired, Credentials);
            }
        }, "AvailableHotelRooms");
    }

    public HotelCancellationPolicyResponse HotelCancellationPolicy(final Integer ResultIndex, final String SessionId, final BookingOptions OptionsForBooking, final AuthenticationData Credentials) throws java.lang.Exception {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (HotelCancellationPolicyResponse) execute(new IWcfMethod() {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                ArrayList<org.kxml2.kdom.Element> __headers = null;
                if (__envelope.headerOut == null) {
                    __headers = new ArrayList<org.kxml2.kdom.Element>();
                } else {
                    __headers = new ArrayList<org.kxml2.kdom.Element>(Arrays.asList(__envelope.headerOut));
                }
                __headers.add(Helper.convertToHeader(Credentials != null ? Credentials : SoapPrimitive.NullNilElement, "http://TekTravel/HotelBookingApi", "Credentials"));
                __envelope.headerOut = __headers.toArray(new Element[__headers.size()]);
                __envelope.addMapping("http://TekTravel/HotelBookingApi", "OptionsForBooking", new BookingOptions().getClass());
                SoapObject __soapReq = new SoapObject("http://TekTravel/HotelBookingApi", "HotelCancellationPolicyRequest");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "ResultIndex";
                __info.type = PropertyInfo.INTEGER_CLASS;
                __info.setValue(ResultIndex);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "SessionId";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(SessionId != null ? SessionId : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "OptionsForBooking";
                __info.type = BookingOptions.class;
                __info.setValue(OptionsForBooking != null ? OptionsForBooking : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                return getResult(HotelCancellationPolicyResponse.class, __result, "HotelCancellationPolicyResponse", __envelope);
            }
        }, "http://TekTravel/HotelBookingApi/HotelCancellationPolicy", __profile);
    }

    public android.os.AsyncTask<Void, Void, OperationResult<HotelCancellationPolicyResponse>> HotelCancellationPolicyAsync(final Integer ResultIndex, final String SessionId, final BookingOptions OptionsForBooking, final AuthenticationData Credentials) {
        return executeAsync(new Functions.IFunc<HotelCancellationPolicyResponse>() {
            public HotelCancellationPolicyResponse Func() throws java.lang.Exception {
                return HotelCancellationPolicy(ResultIndex, SessionId, OptionsForBooking, Credentials);
            }
        }, "HotelCancellationPolicy");
    }

    public HotelCancellationPolicyResponse HotelCancellationPolicyForAllRooms(final Integer ResultIndex, final String SessionId, final BookingOptions OptionsForBooking, final AuthenticationData Credentials) throws java.lang.Exception {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (HotelCancellationPolicyResponse) execute(new IWcfMethod() {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                ArrayList<org.kxml2.kdom.Element> __headers = null;
                if (__envelope.headerOut == null) {
                    __headers = new ArrayList<org.kxml2.kdom.Element>();
                } else {
                    __headers = new ArrayList<org.kxml2.kdom.Element>(Arrays.asList(__envelope.headerOut));
                }
                __headers.add(Helper.convertToHeader(Credentials != null ? Credentials : SoapPrimitive.NullNilElement, "http://TekTravel/HotelBookingApi", "Credentials"));
                __envelope.headerOut = __headers.toArray(new Element[__headers.size()]);
                __envelope.addMapping("http://TekTravel/HotelBookingApi", "OptionsForBooking", new BookingOptions().getClass());
                SoapObject __soapReq = new SoapObject("http://TekTravel/HotelBookingApi", "HotelCancellationPolicyRequest");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "ResultIndex";
                __info.type = PropertyInfo.INTEGER_CLASS;
                __info.setValue(ResultIndex);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "SessionId";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(SessionId != null ? SessionId : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "OptionsForBooking";
                __info.type = BookingOptions.class;
                __info.setValue(OptionsForBooking != null ? OptionsForBooking : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                return getResult(HotelCancellationPolicyResponse.class, __result, "HotelCancellationPolicyResponse", __envelope);
            }
        }, "http://TekTravel/HotelBookingApi/HotelCancellationPolicyForAllRooms", __profile);
    }

    public android.os.AsyncTask<Void, Void, OperationResult<HotelCancellationPolicyResponse>> HotelCancellationPolicyForAllRoomsAsync(final Integer ResultIndex, final String SessionId, final BookingOptions OptionsForBooking, final AuthenticationData Credentials) {
        return executeAsync(new Functions.IFunc<HotelCancellationPolicyResponse>() {
            public HotelCancellationPolicyResponse Func() throws java.lang.Exception {
                return HotelCancellationPolicyForAllRooms(ResultIndex, SessionId, OptionsForBooking, Credentials);
            }
        }, "HotelCancellationPolicyForAllRooms");
    }

    public HotelBookResponse HotelBook(final String ClientReferenceNumber, final String GuestNationality, final ArrayOfGuest Guests, final AddressInfo AddressInfo, final PaymentInfo PaymentInfo, final String SessionId, final FlightInfo FlightInfo, final Integer NoOfRooms, final Integer ResultIndex, final String HotelCode, final String HotelName, final ArrayOfRequestedRooms HotelRooms, final ArrayOfSpecialRequest SpecialRequests, final String AgencyReferenceNumber, final Boolean RestrictDuplicateBooking, final AuthenticationData Credentials) throws java.lang.Exception {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (HotelBookResponse) execute(new IWcfMethod() {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                ArrayList<org.kxml2.kdom.Element> __headers = null;
                if (__envelope.headerOut == null) {
                    __headers = new ArrayList<org.kxml2.kdom.Element>();
                } else {
                    __headers = new ArrayList<org.kxml2.kdom.Element>(Arrays.asList(__envelope.headerOut));
                }
                __headers.add(Helper.convertToHeader(Credentials != null ? Credentials : SoapPrimitive.NullNilElement, "http://TekTravel/HotelBookingApi", "Credentials"));
                __envelope.headerOut = __headers.toArray(new Element[__headers.size()]);
                __envelope.addMapping("http://TekTravel/HotelBookingApi", "Guests", new ArrayOfGuest().getClass());
                __envelope.addMapping("http://TekTravel/HotelBookingApi", "AddressInfo", new AddressInfo().getClass());
                __envelope.addMapping("http://TekTravel/HotelBookingApi", "PaymentInfo", new PaymentInfo().getClass());
                __envelope.addMapping("http://TekTravel/HotelBookingApi", "FlightInfo", new FlightInfo().getClass());
                __envelope.addMapping("http://TekTravel/HotelBookingApi", "HotelRooms", new ArrayOfRequestedRooms().getClass());
                __envelope.addMapping("http://TekTravel/HotelBookingApi", "SpecialRequests", new ArrayOfSpecialRequest().getClass());
                SoapObject __soapReq = new SoapObject("http://TekTravel/HotelBookingApi", "HotelBookRequest");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "ClientReferenceNumber";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(ClientReferenceNumber != null ? ClientReferenceNumber : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "GuestNationality";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(GuestNationality != null ? GuestNationality : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "Guests";
                __info.type = PropertyInfo.VECTOR_CLASS;
                __info.setValue(Guests != null ? Guests : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "AddressInfo";
                __info.type = AddressInfo.class;
                __info.setValue(AddressInfo != null ? AddressInfo : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "PaymentInfo";
                __info.type = PaymentInfo.class;
                __info.setValue(PaymentInfo != null ? PaymentInfo : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "SessionId";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(SessionId != null ? SessionId : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "FlightInfo";
                __info.type = FlightInfo.class;
                __info.setValue(FlightInfo != null ? FlightInfo : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "NoOfRooms";
                __info.type = PropertyInfo.INTEGER_CLASS;
                __info.setValue(NoOfRooms);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "ResultIndex";
                __info.type = PropertyInfo.INTEGER_CLASS;
                __info.setValue(ResultIndex);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "HotelCode";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(HotelCode != null ? HotelCode : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "HotelName";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(HotelName != null ? HotelName : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "HotelRooms";
                __info.type = PropertyInfo.VECTOR_CLASS;
                __info.setValue(HotelRooms != null ? HotelRooms : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "SpecialRequests";
                __info.type = PropertyInfo.VECTOR_CLASS;
                __info.setValue(SpecialRequests != null ? SpecialRequests : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "AgencyReferenceNumber";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(AgencyReferenceNumber != null ? AgencyReferenceNumber : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "RestrictDuplicateBooking";
                __info.type = PropertyInfo.BOOLEAN_CLASS;
                __info.setValue(RestrictDuplicateBooking);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                return getResult(HotelBookResponse.class, __result, "HotelBookResponse", __envelope);
            }
        }, "http://TekTravel/HotelBookingApi/HotelBook", __profile);
    }

    public android.os.AsyncTask<Void, Void, OperationResult<HotelBookResponse>> HotelBookAsync(final String ClientReferenceNumber, final String GuestNationality, final ArrayOfGuest Guests, final AddressInfo AddressInfo, final PaymentInfo PaymentInfo, final String SessionId, final FlightInfo FlightInfo, final Integer NoOfRooms, final Integer ResultIndex, final String HotelCode, final String HotelName, final ArrayOfRequestedRooms HotelRooms, final ArrayOfSpecialRequest SpecialRequests, final String AgencyReferenceNumber, final Boolean RestrictDuplicateBooking, final AuthenticationData Credentials) {
        return executeAsync(new Functions.IFunc<HotelBookResponse>() {
            public HotelBookResponse Func() throws java.lang.Exception {
                return HotelBook(ClientReferenceNumber, GuestNationality, Guests, AddressInfo, PaymentInfo, SessionId, FlightInfo, NoOfRooms, ResultIndex, HotelCode, HotelName, HotelRooms, SpecialRequests, AgencyReferenceNumber, RestrictDuplicateBooking, Credentials);
            }
        }, "HotelBook");
    }

    public AvailabilityAndPricingResponse AvailabilityAndPricing(final Integer ResultIndex, final String SessionId, final BookingOptions OptionsForBooking, final AuthenticationData Credentials) throws java.lang.Exception {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (AvailabilityAndPricingResponse) execute(new IWcfMethod() {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                ArrayList<org.kxml2.kdom.Element> __headers = null;
                if (__envelope.headerOut == null) {
                    __headers = new ArrayList<org.kxml2.kdom.Element>();
                } else {
                    __headers = new ArrayList<org.kxml2.kdom.Element>(Arrays.asList(__envelope.headerOut));
                }
                __headers.add(Helper.convertToHeader(Credentials != null ? Credentials : SoapPrimitive.NullNilElement, "http://TekTravel/HotelBookingApi", "Credentials"));
                __envelope.headerOut = __headers.toArray(new Element[__headers.size()]);
                __envelope.addMapping("http://TekTravel/HotelBookingApi", "OptionsForBooking", new BookingOptions().getClass());
                SoapObject __soapReq = new SoapObject("http://TekTravel/HotelBookingApi", "AvailabilityAndPricingRequest");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "ResultIndex";
                __info.type = PropertyInfo.INTEGER_CLASS;
                __info.setValue(ResultIndex);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "SessionId";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(SessionId != null ? SessionId : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "OptionsForBooking";
                __info.type = BookingOptions.class;
                __info.setValue(OptionsForBooking != null ? OptionsForBooking : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                return getResult(AvailabilityAndPricingResponse.class, __result, "AvailabilityAndPricingResponse", __envelope);
            }
        }, "http://TekTravel/HotelBookingApi/AvailabilityAndPricing", __profile);
    }

    public android.os.AsyncTask<Void, Void, OperationResult<AvailabilityAndPricingResponse>> AvailabilityAndPricingAsync(final Integer ResultIndex, final String SessionId, final BookingOptions OptionsForBooking, final AuthenticationData Credentials) {
        return executeAsync(new Functions.IFunc<AvailabilityAndPricingResponse>() {
            public AvailabilityAndPricingResponse Func() throws java.lang.Exception {
                return AvailabilityAndPricing(ResultIndex, SessionId, OptionsForBooking, Credentials);
            }
        }, "AvailabilityAndPricing");
    }

    public HotelBookingDetailResponse HotelBookingDetail(final Integer BookingId, final String ConfirmationNo, final String ClientReferenceNumber, final AuthenticationData Credentials) throws java.lang.Exception {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (HotelBookingDetailResponse) execute(new IWcfMethod() {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                ArrayList<org.kxml2.kdom.Element> __headers = null;
                if (__envelope.headerOut == null) {
                    __headers = new ArrayList<org.kxml2.kdom.Element>();
                } else {
                    __headers = new ArrayList<org.kxml2.kdom.Element>(Arrays.asList(__envelope.headerOut));
                }
                __headers.add(Helper.convertToHeader(Credentials != null ? Credentials : SoapPrimitive.NullNilElement, "http://TekTravel/HotelBookingApi", "Credentials"));
                __envelope.headerOut = __headers.toArray(new Element[__headers.size()]);
                SoapObject __soapReq = new SoapObject("http://TekTravel/HotelBookingApi", "HotelBookingDetailRequest");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "BookingId";
                __info.type = PropertyInfo.INTEGER_CLASS;
                __info.setValue(BookingId);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "ConfirmationNo";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(ConfirmationNo != null ? ConfirmationNo : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "ClientReferenceNumber";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(ClientReferenceNumber != null ? ClientReferenceNumber : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                return getResult(HotelBookingDetailResponse.class, __result, "HotelBookingDetailResponse", __envelope);
            }
        }, "http://TekTravel/HotelBookingApi/HotelBookingDetail", __profile);
    }

    public android.os.AsyncTask<Void, Void, OperationResult<HotelBookingDetailResponse>> HotelBookingDetailAsync(final Integer BookingId, final String ConfirmationNo, final String ClientReferenceNumber, final AuthenticationData Credentials) {
        return executeAsync(new Functions.IFunc<HotelBookingDetailResponse>() {
            public HotelBookingDetailResponse Func() throws java.lang.Exception {
                return HotelBookingDetail(BookingId, ConfirmationNo, ClientReferenceNumber, Credentials);
            }
        }, "HotelBookingDetail");
    }

    public GenerateInvoiceResponse GenerateInvoice(final Integer BookingId, final String ConfirmationNo, final PaymentInfo PaymentInfo, final AuthenticationData Credentials) throws java.lang.Exception {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (GenerateInvoiceResponse) execute(new IWcfMethod() {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                ArrayList<org.kxml2.kdom.Element> __headers = null;
                if (__envelope.headerOut == null) {
                    __headers = new ArrayList<org.kxml2.kdom.Element>();
                } else {
                    __headers = new ArrayList<org.kxml2.kdom.Element>(Arrays.asList(__envelope.headerOut));
                }
                __headers.add(Helper.convertToHeader(Credentials != null ? Credentials : SoapPrimitive.NullNilElement, "http://TekTravel/HotelBookingApi", "Credentials"));
                __envelope.headerOut = __headers.toArray(new Element[__headers.size()]);
                __envelope.addMapping("http://TekTravel/HotelBookingApi", "PaymentInfo", new PaymentInfo().getClass());
                SoapObject __soapReq = new SoapObject("http://TekTravel/HotelBookingApi", "GenerateInvoiceRequest");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "BookingId";
                __info.type = PropertyInfo.INTEGER_CLASS;
                __info.setValue(BookingId);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "ConfirmationNo";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(ConfirmationNo != null ? ConfirmationNo : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "PaymentInfo";
                __info.type = PaymentInfo.class;
                __info.setValue(PaymentInfo != null ? PaymentInfo : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                return getResult(GenerateInvoiceResponse.class, __result, "GenerateInvoiceResponse", __envelope);
            }
        }, "http://TekTravel/HotelBookingApi/GenerateInvoice", __profile);
    }

    public android.os.AsyncTask<Void, Void, OperationResult<GenerateInvoiceResponse>> GenerateInvoiceAsync(final Integer BookingId, final String ConfirmationNo, final PaymentInfo PaymentInfo, final AuthenticationData Credentials) {
        return executeAsync(new Functions.IFunc<GenerateInvoiceResponse>() {
            public GenerateInvoiceResponse Func() throws java.lang.Exception {
                return GenerateInvoice(BookingId, ConfirmationNo, PaymentInfo, Credentials);
            }
        }, "GenerateInvoice");
    }

    public AmendmentResponse Amendment(final AmendmentRequestType Request, final Integer BookingId, final AmendInformation AmendInformation, final String ConfirmationNo, final AuthenticationData Credentials) throws java.lang.Exception {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (AmendmentResponse) execute(new IWcfMethod() {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                ArrayList<org.kxml2.kdom.Element> __headers = null;
                if (__envelope.headerOut == null) {
                    __headers = new ArrayList<org.kxml2.kdom.Element>();
                } else {
                    __headers = new ArrayList<org.kxml2.kdom.Element>(Arrays.asList(__envelope.headerOut));
                }
                __headers.add(Helper.convertToHeader(Credentials != null ? Credentials : SoapPrimitive.NullNilElement, "http://TekTravel/HotelBookingApi", "Credentials"));
                __envelope.headerOut = __headers.toArray(new Element[__headers.size()]);
                __envelope.addMapping("http://TekTravel/HotelBookingApi", "Request", new AmendmentRequestType().getClass());
                __envelope.addMapping("http://TekTravel/HotelBookingApi", "AmendInformation", new AmendInformation().getClass());
                SoapObject __soapReq = new SoapObject("http://TekTravel/HotelBookingApi", "AmendmentRequest");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "Request";
                __info.type = AmendmentRequestType.class;
                __info.setValue(Request != null ? Request : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "BookingId";
                __info.type = PropertyInfo.INTEGER_CLASS;
                __info.setValue(BookingId);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "AmendInformation";
                __info.type = AmendInformation.class;
                __info.setValue(AmendInformation != null ? AmendInformation : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "ConfirmationNo";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(ConfirmationNo != null ? ConfirmationNo : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                return getResult(AmendmentResponse.class, __result, "AmendmentResponse", __envelope);
            }
        }, "http://TekTravel/HotelBookingApi/Amendment", __profile);
    }

    public android.os.AsyncTask<Void, Void, OperationResult<AmendmentResponse>> AmendmentAsync(final AmendmentRequestType Request, final Integer BookingId, final AmendInformation AmendInformation, final String ConfirmationNo, final AuthenticationData Credentials) {
        return executeAsync(new Functions.IFunc<AmendmentResponse>() {
            public AmendmentResponse Func() throws java.lang.Exception {
                return Amendment(Request, BookingId, AmendInformation, ConfirmationNo, Credentials);
            }
        }, "Amendment");
    }

    public HotelCancelResponse HotelCancel(final Integer BookingId, final Enums.CancelRequestType RequestType, final String Remarks, final String ConfirmationNo, final AuthenticationData Credentials) throws java.lang.Exception {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (HotelCancelResponse) execute(new IWcfMethod() {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                ArrayList<org.kxml2.kdom.Element> __headers = null;
                if (__envelope.headerOut == null) {
                    __headers = new ArrayList<org.kxml2.kdom.Element>();
                } else {
                    __headers = new ArrayList<org.kxml2.kdom.Element>(Arrays.asList(__envelope.headerOut));
                }
                __headers.add(Helper.convertToHeader(Credentials != null ? Credentials : SoapPrimitive.NullNilElement, "http://TekTravel/HotelBookingApi", "Credentials"));
                __envelope.headerOut = __headers.toArray(new Element[__headers.size()]);
                SoapObject __soapReq = new SoapObject("http://TekTravel/HotelBookingApi", "HotelCancelRequest");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "BookingId";
                __info.type = PropertyInfo.INTEGER_CLASS;
                __info.setValue(BookingId);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "RequestType";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(RequestType != null ? RequestType.toString() : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "Remarks";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(Remarks != null ? Remarks : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "ConfirmationNo";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(ConfirmationNo != null ? ConfirmationNo : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                return getResult(HotelCancelResponse.class, __result, "HotelCancelResponse", __envelope);
            }
        }, "http://TekTravel/HotelBookingApi/HotelCancel", __profile);
    }

    public android.os.AsyncTask<Void, Void, OperationResult<HotelCancelResponse>> HotelCancelAsync(final Integer BookingId, final Enums.CancelRequestType RequestType, final String Remarks, final String ConfirmationNo, final AuthenticationData Credentials) {
        return executeAsync(new Functions.IFunc<HotelCancelResponse>() {
            public HotelCancelResponse Func() throws java.lang.Exception {
                return HotelCancel(BookingId, RequestType, Remarks, ConfirmationNo, Credentials);
            }
        }, "HotelCancel");
    }

    public CountryListResponse CountryList(final AuthenticationData Credentials) throws java.lang.Exception {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (CountryListResponse) execute(new IWcfMethod() {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                ArrayList<org.kxml2.kdom.Element> __headers = null;
                if (__envelope.headerOut == null) {
                    __headers = new ArrayList<org.kxml2.kdom.Element>();
                } else {
                    __headers = new ArrayList<org.kxml2.kdom.Element>(Arrays.asList(__envelope.headerOut));
                }
                __headers.add(Helper.convertToHeader(Credentials != null ? Credentials : SoapPrimitive.NullNilElement, "http://TekTravel/HotelBookingApi", "Credentials"));
                __envelope.headerOut = __headers.toArray(new Element[__headers.size()]);
                SoapObject __soapReq = new SoapObject("http://TekTravel/HotelBookingApi", "CountryListRequest");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                return getResult(CountryListResponse.class, __result, "CountryListResponse", __envelope);
            }
        }, "http://TekTravel/HotelBookingApi/CountryList", __profile);
    }

    public android.os.AsyncTask<Void, Void, OperationResult<CountryListResponse>> CountryListAsync(final AuthenticationData Credentials) {
        return executeAsync(new Functions.IFunc<CountryListResponse>() {
            public CountryListResponse Func() throws java.lang.Exception {
                return CountryList(Credentials);
            }
        }, "CountryList");
    }

    public DestinationCityListResponse DestinationCityList(final String CountryCode, final String ReturnNewCityCodes, final AuthenticationData Credentials) throws java.lang.Exception {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (DestinationCityListResponse) execute(new IWcfMethod() {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                ArrayList<org.kxml2.kdom.Element> __headers = null;
                if (__envelope.headerOut == null) {
                    __headers = new ArrayList<org.kxml2.kdom.Element>();
                } else {
                    __headers = new ArrayList<org.kxml2.kdom.Element>(Arrays.asList(__envelope.headerOut));
                }
                __headers.add(Helper.convertToHeader(Credentials != null ? Credentials : SoapPrimitive.NullNilElement, "http://TekTravel/HotelBookingApi", "Credentials"));
                __envelope.headerOut = __headers.toArray(new Element[__headers.size()]);
                SoapObject __soapReq = new SoapObject("http://TekTravel/HotelBookingApi", "DestinationCityListRequest");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "CountryCode";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(CountryCode != null ? CountryCode : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "ReturnNewCityCodes";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(ReturnNewCityCodes != null ? ReturnNewCityCodes : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                return getResult(DestinationCityListResponse.class, __result, "DestinationCityListResponse", __envelope);
            }
        }, "http://TekTravel/HotelBookingApi/DestinationCityList", __profile);
    }

    public android.os.AsyncTask<Void, Void, OperationResult<DestinationCityListResponse>> DestinationCityListAsync(final String CountryCode, final String ReturnNewCityCodes, final AuthenticationData Credentials) {
        return executeAsync(new Functions.IFunc<DestinationCityListResponse>() {
            public DestinationCityListResponse Func() throws java.lang.Exception {
                return DestinationCityList(CountryCode, ReturnNewCityCodes, Credentials);
            }
        }, "DestinationCityList");
    }

    public TopDestinationsResponse TopDestinations(final AuthenticationData Credentials) throws java.lang.Exception {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (TopDestinationsResponse) execute(new IWcfMethod() {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                ArrayList<org.kxml2.kdom.Element> __headers = null;
                if (__envelope.headerOut == null) {
                    __headers = new ArrayList<org.kxml2.kdom.Element>();
                } else {
                    __headers = new ArrayList<org.kxml2.kdom.Element>(Arrays.asList(__envelope.headerOut));
                }
                __headers.add(Helper.convertToHeader(Credentials != null ? Credentials : SoapPrimitive.NullNilElement, "http://TekTravel/HotelBookingApi", "Credentials"));
                __envelope.headerOut = __headers.toArray(new Element[__headers.size()]);
                SoapObject __soapReq = new SoapObject("http://TekTravel/HotelBookingApi", "TopDestinationsRequest");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                return getResult(TopDestinationsResponse.class, __result, "TopDestinationsResponse", __envelope);
            }
        }, "http://TekTravel/HotelBookingApi/TopDestinations", __profile);
    }

    public android.os.AsyncTask<Void, Void, OperationResult<TopDestinationsResponse>> TopDestinationsAsync(final AuthenticationData Credentials) {
        return executeAsync(new Functions.IFunc<TopDestinationsResponse>() {
            public TopDestinationsResponse Func() throws java.lang.Exception {
                return TopDestinations(Credentials);
            }
        }, "TopDestinations");
    }

    public HotelDetailsResponse HotelDetails(final Integer ResultIndex, final String SessionId, final String HotelCode, final String Language, final AuthenticationData Credentials) throws java.lang.Exception {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (HotelDetailsResponse) execute(new IWcfMethod() {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                ArrayList<org.kxml2.kdom.Element> __headers = null;
                if (__envelope.headerOut == null) {
                    __headers = new ArrayList<org.kxml2.kdom.Element>();
                } else {
                    __headers = new ArrayList<org.kxml2.kdom.Element>(Arrays.asList(__envelope.headerOut));
                }
                __headers.add(Helper.convertToHeader(Credentials != null ? Credentials : SoapPrimitive.NullNilElement, "http://TekTravel/HotelBookingApi", "Credentials"));
                __envelope.headerOut = __headers.toArray(new Element[__headers.size()]);
                SoapObject __soapReq = new SoapObject("http://TekTravel/HotelBookingApi", "HotelDetailsRequest");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "ResultIndex";
                __info.type = PropertyInfo.INTEGER_CLASS;
                __info.setValue(ResultIndex);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "SessionId";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(SessionId != null ? SessionId : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "HotelCode";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(HotelCode != null ? HotelCode : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "Language";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(Language != null ? Language : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                return getResult(HotelDetailsResponse.class, __result, "HotelDetailsResponse", __envelope);
            }
        }, "http://TekTravel/HotelBookingApi/HotelDetails", __profile);
    }

    public android.os.AsyncTask<Void, Void, OperationResult<HotelDetailsResponse>> HotelDetailsAsync(final Integer ResultIndex, final String SessionId, final String HotelCode, final String Language, final AuthenticationData Credentials) {
        return executeAsync(new Functions.IFunc<HotelDetailsResponse>() {
            public HotelDetailsResponse Func() throws java.lang.Exception {
                return HotelDetails(ResultIndex, SessionId, HotelCode, Language, Credentials);
            }
        }, "HotelDetails");
    }

    public HotelCodesResponse HotelCodeList(final AuthenticationData Credentials) throws java.lang.Exception {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (HotelCodesResponse) execute(new IWcfMethod() {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                ArrayList<org.kxml2.kdom.Element> __headers = null;
                if (__envelope.headerOut == null) {
                    __headers = new ArrayList<org.kxml2.kdom.Element>();
                } else {
                    __headers = new ArrayList<org.kxml2.kdom.Element>(Arrays.asList(__envelope.headerOut));
                }
                __headers.add(Helper.convertToHeader(Credentials != null ? Credentials : SoapPrimitive.NullNilElement, "http://TekTravel/HotelBookingApi", "Credentials"));
                __envelope.headerOut = __headers.toArray(new Element[__headers.size()]);
                SoapObject __soapReq = new SoapObject("http://TekTravel/HotelBookingApi", "HotelCodesRequest");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                return getResult(HotelCodesResponse.class, __result, "HotelCodesResponse", __envelope);
            }
        }, "http://TekTravel/HotelBookingApi/HotelCodes", __profile);
    }

    public android.os.AsyncTask<Void, Void, OperationResult<HotelCodesResponse>> HotelCodeListAsync(final AuthenticationData Credentials) {
        return executeAsync(new Functions.IFunc<HotelCodesResponse>() {
            public HotelCodesResponse Func() throws java.lang.Exception {
                return HotelCodeList(Credentials);
            }
        }, "HotelCodeList");
    }

    public HotelSearchWithRoomsResponse HotelSearchWithRooms(final org.joda.time.DateTime CheckInDate, final org.joda.time.DateTime CheckOutDate, final String CountryName, final String CityName, final Integer CityId, final Boolean IsNearBySearchAllowed, final Integer NoOfRooms, final String GuestNationality, final ArrayOfRoomGuest RoomGuests, final String PreferredCurrencyCode, final Integer ResultCount, final HotelSearchWithRoomsFilters Filters, final Integer ResponseTime, final Boolean IsCancellationPolicyRequired, final AuthenticationData Credentials) throws java.lang.Exception {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (HotelSearchWithRoomsResponse) execute(new IWcfMethod() {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                ArrayList<org.kxml2.kdom.Element> __headers = null;
                if (__envelope.headerOut == null) {
                    __headers = new ArrayList<org.kxml2.kdom.Element>();
                } else {
                    __headers = new ArrayList<org.kxml2.kdom.Element>(Arrays.asList(__envelope.headerOut));
                }
                __headers.add(Helper.convertToHeader(Credentials != null ? Credentials : SoapPrimitive.NullNilElement, "http://TekTravel/HotelBookingApi", "Credentials"));
                __envelope.headerOut = __headers.toArray(new Element[__headers.size()]);
                __envelope.addMapping("http://TekTravel/HotelBookingApi", "RoomGuests", new ArrayOfRoomGuest().getClass());
                __envelope.addMapping("http://TekTravel/HotelBookingApi", "Filters", new HotelSearchWithRoomsFilters().getClass());
                SoapObject __soapReq = new SoapObject("http://TekTravel/HotelBookingApi", "HotelSearchWithRoomsRequest");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "CheckInDate";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(CheckInDate != null ? CheckInDate.toString() : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "CheckOutDate";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(CheckOutDate != null ? CheckOutDate.toString() : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "CountryName";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(CountryName != null ? CountryName : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "CityName";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(CityName != null ? CityName : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "CityId";
                __info.type = PropertyInfo.INTEGER_CLASS;
                __info.setValue(CityId);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "IsNearBySearchAllowed";
                __info.type = PropertyInfo.BOOLEAN_CLASS;
                __info.setValue(IsNearBySearchAllowed);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "NoOfRooms";
                __info.type = PropertyInfo.INTEGER_CLASS;
                __info.setValue(NoOfRooms);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "GuestNationality";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(GuestNationality != null ? GuestNationality : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "RoomGuests";
                __info.type = PropertyInfo.VECTOR_CLASS;
                __info.setValue(RoomGuests != null ? RoomGuests : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "PreferredCurrencyCode";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(PreferredCurrencyCode != null ? PreferredCurrencyCode : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "ResultCount";
                __info.type = PropertyInfo.INTEGER_CLASS;
                __info.setValue(ResultCount);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "Filters";
                __info.type = HotelSearchWithRoomsFilters.class;
                __info.setValue(Filters != null ? Filters : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "ResponseTime";
                __info.type = PropertyInfo.INTEGER_CLASS;
                __info.setValue(ResponseTime);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "IsCancellationPolicyRequired";
                __info.type = PropertyInfo.BOOLEAN_CLASS;
                __info.setValue(IsCancellationPolicyRequired);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                return getResult(HotelSearchWithRoomsResponse.class, __result, "HotelSearchWithRoomsResponse", __envelope);
            }
        }, "http://TekTravel/HotelBookingApi/HotelSearchWithRooms", __profile);
    }

    public android.os.AsyncTask<Void, Void, OperationResult<HotelSearchWithRoomsResponse>> HotelSearchWithRoomsAsync(final org.joda.time.DateTime CheckInDate, final org.joda.time.DateTime CheckOutDate, final String CountryName, final String CityName, final Integer CityId, final Boolean IsNearBySearchAllowed, final Integer NoOfRooms, final String GuestNationality, final ArrayOfRoomGuest RoomGuests, final String PreferredCurrencyCode, final Integer ResultCount, final HotelSearchWithRoomsFilters Filters, final Integer ResponseTime, final Boolean IsCancellationPolicyRequired, final AuthenticationData Credentials) {
        return executeAsync(new Functions.IFunc<HotelSearchWithRoomsResponse>() {
            public HotelSearchWithRoomsResponse Func() throws java.lang.Exception {
                return HotelSearchWithRooms(CheckInDate, CheckOutDate, CountryName, CityName, CityId, IsNearBySearchAllowed, NoOfRooms, GuestNationality, RoomGuests, PreferredCurrencyCode, ResultCount, Filters, ResponseTime, IsCancellationPolicyRequired, Credentials);
            }
        }, "HotelSearchWithRooms");
    }

    public HotelBookingDetailBasedOnDateResponse HotelBookingDetailBasedOnDate(final org.joda.time.DateTime FromDate, final org.joda.time.DateTime ToDate, final AuthenticationData Credentials) throws java.lang.Exception {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (HotelBookingDetailBasedOnDateResponse) execute(new IWcfMethod() {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                ArrayList<org.kxml2.kdom.Element> __headers = null;
                if (__envelope.headerOut == null) {
                    __headers = new ArrayList<org.kxml2.kdom.Element>();
                } else {
                    __headers = new ArrayList<org.kxml2.kdom.Element>(Arrays.asList(__envelope.headerOut));
                }
                __headers.add(Helper.convertToHeader(Credentials != null ? Credentials : SoapPrimitive.NullNilElement, "http://TekTravel/HotelBookingApi", "Credentials"));
                __envelope.headerOut = __headers.toArray(new Element[__headers.size()]);
                SoapObject __soapReq = new SoapObject("http://TekTravel/HotelBookingApi", "HotelBookingDetailBasedOnDateRequest");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "FromDate";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(FromDate != null ? FromDate.toString() : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "ToDate";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(ToDate != null ? ToDate.toString() : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                return getResult(HotelBookingDetailBasedOnDateResponse.class, __result, "HotelBookingDetailBasedOnDateResponse", __envelope);
            }
        }, "http://TekTravel/HotelBookingApi/HotelBookingDetailBasedOnDate", __profile);
    }

    public android.os.AsyncTask<Void, Void, OperationResult<HotelBookingDetailBasedOnDateResponse>> HotelBookingDetailBasedOnDateAsync(final org.joda.time.DateTime FromDate, final org.joda.time.DateTime ToDate, final AuthenticationData Credentials) {
        return executeAsync(new Functions.IFunc<HotelBookingDetailBasedOnDateResponse>() {
            public HotelBookingDetailBasedOnDateResponse Func() throws java.lang.Exception {
                return HotelBookingDetailBasedOnDate(FromDate, ToDate, Credentials);
            }
        }, "HotelBookingDetailBasedOnDate");
    }

    public GiataHotelCodesResponse GiataHotelCodeList(final String CityCode, final String IsDetailedResponse, final AuthenticationData Credentials) throws java.lang.Exception {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (GiataHotelCodesResponse) execute(new IWcfMethod() {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                ArrayList<org.kxml2.kdom.Element> __headers = null;
                if (__envelope.headerOut == null) {
                    __headers = new ArrayList<org.kxml2.kdom.Element>();
                } else {
                    __headers = new ArrayList<org.kxml2.kdom.Element>(Arrays.asList(__envelope.headerOut));
                }
                __headers.add(Helper.convertToHeader(Credentials != null ? Credentials : SoapPrimitive.NullNilElement, "http://TekTravel/HotelBookingApi", "Credentials"));
                __envelope.headerOut = __headers.toArray(new Element[__headers.size()]);
                SoapObject __soapReq = new SoapObject("http://TekTravel/HotelBookingApi", "GiataHotelCodesRequest");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "CityCode";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(CityCode != null ? CityCode : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://TekTravel/HotelBookingApi";
                __info.name = "IsDetailedResponse";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(IsDetailedResponse != null ? IsDetailedResponse : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                return getResult(GiataHotelCodesResponse.class, __result, "GiataHotelCodesResponse", __envelope);
            }
        }, "http://TekTravel/HotelBookingApi/GiataHotelCodes", __profile);
    }

    public android.os.AsyncTask<Void, Void, OperationResult<GiataHotelCodesResponse>> GiataHotelCodeListAsync(final String CityCode, final String IsDetailedResponse, final AuthenticationData Credentials) {
        return executeAsync(new Functions.IFunc<GiataHotelCodesResponse>() {
            public GiataHotelCodesResponse Func() throws java.lang.Exception {
                return GiataHotelCodeList(CityCode, IsDetailedResponse, Credentials);
            }
        }, "GiataHotelCodeList");
    }

    public TagInfoResponse TagInfo(final AuthenticationData Credentials) throws java.lang.Exception {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (TagInfoResponse) execute(new IWcfMethod() {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                ArrayList<org.kxml2.kdom.Element> __headers = null;
                if (__envelope.headerOut == null) {
                    __headers = new ArrayList<org.kxml2.kdom.Element>();
                } else {
                    __headers = new ArrayList<org.kxml2.kdom.Element>(Arrays.asList(__envelope.headerOut));
                }
                __headers.add(Helper.convertToHeader(Credentials != null ? Credentials : SoapPrimitive.NullNilElement, "http://TekTravel/HotelBookingApi", "Credentials"));
                __envelope.headerOut = __headers.toArray(new Element[__headers.size()]);
                SoapObject __soapReq = new SoapObject("http://TekTravel/HotelBookingApi", "TagInfoRequest");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                return getResult(TagInfoResponse.class, __result, "TagInfoResponse", __envelope);
            }
        }, "http://TekTravel/HotelBookingApi/TagInfos", __profile);
    }

    public android.os.AsyncTask<Void, Void, OperationResult<TagInfoResponse>> TagInfoAsync(final AuthenticationData Credentials) {
        return executeAsync(new Functions.IFunc<TagInfoResponse>() {
            public TagInfoResponse Func() throws java.lang.Exception {
                return TagInfo(Credentials);
            }
        }, "TagInfo");
    }

    public CityWiseNotificationResponse CityWiseNotification(final AuthenticationData Credentials) throws java.lang.Exception {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (CityWiseNotificationResponse) execute(new IWcfMethod() {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                ArrayList<org.kxml2.kdom.Element> __headers = null;
                if (__envelope.headerOut == null) {
                    __headers = new ArrayList<org.kxml2.kdom.Element>();
                } else {
                    __headers = new ArrayList<org.kxml2.kdom.Element>(Arrays.asList(__envelope.headerOut));
                }
                __headers.add(Helper.convertToHeader(Credentials != null ? Credentials : SoapPrimitive.NullNilElement, "http://TekTravel/HotelBookingApi", "Credentials"));
                __envelope.headerOut = __headers.toArray(new Element[__headers.size()]);
                SoapObject __soapReq = new SoapObject("http://TekTravel/HotelBookingApi", "CityWiseNotificationRequest");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                return getResult(CityWiseNotificationResponse.class, __result, "CityWiseNotificationResponse", __envelope);
            }
        }, "http://TekTravel/HotelBookingApi/CityWiseNotification", __profile);
    }

    public android.os.AsyncTask<Void, Void, OperationResult<CityWiseNotificationResponse>> CityWiseNotificationAsync(final AuthenticationData Credentials) {
        return executeAsync(new Functions.IFunc<CityWiseNotificationResponse>() {
            public CityWiseNotificationResponse Func() throws java.lang.Exception {
                return CityWiseNotification(Credentials);
            }
        }, "CityWiseNotification");
    }

    protected java.lang.Object execute(IWcfMethod wcfMethod, String methodName, com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile profile) throws java.lang.Exception {
        org.ksoap2.transport.Transport __httpTransport = createTransport();
        __httpTransport.debug = enableLogging;
        ExtendedSoapSerializationEnvelope __envelope = wcfMethod.CreateSoapEnvelope();
        try {
            sendRequest(methodName, __envelope, __httpTransport, profile);

        } finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    android.util.Log.i("requestDump", __httpTransport.requestDump);

                }
                if (__httpTransport.responseDump != null) {
                    android.util.Log.i("responseDump", __httpTransport.responseDump);
                }
            }
        }
        java.lang.Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault) {
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault) __retObj;
            throw convertToException(__fault, __envelope);
        } else {
            return wcfMethod.ProcessResult(__envelope, __retObj);
        }
    }

    protected <T> android.os.AsyncTask<Void, Void, OperationResult<T>> executeAsync(final Functions.IFunc<T> func, final String methodName) {
        return new android.os.AsyncTask<Void, Void, OperationResult<T>>() {
            @Override
            protected void onPreExecute() {
                callback.Starting();
            }

            @Override
            protected OperationResult<T> doInBackground(Void... params) {
                OperationResult<T> result = new OperationResult<T>();
                try {
                    result.MethodName = methodName;
                    result.Result = func.Func();
                } catch (java.lang.Exception ex) {
                    ex.printStackTrace();
                    result.Exception = ex;
                }
                return result;
            }

            @Override
            protected void onPostExecute(OperationResult<T> result) {
                callback.Completed(result);
            }
        }.execute();
    }

    protected java.lang.Exception convertToException(org.ksoap2.SoapFault fault, ExtendedSoapSerializationEnvelope envelope) {
        org.ksoap2.SoapFault newException = fault;

        return newException;
    }

    interface IWcfMethod {
        ExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws java.lang.Exception;

        java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object result) throws java.lang.Exception;
    }
}


