package com.Tamm.Hotels.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.6.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.AttributeInfo;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.ArrayList;
import java.util.Hashtable;

public class CancelPolicies extends AttributeContainer implements KvmSerializable {

    
    public org.joda.time.DateTime LastCancellationDeadline;

    public ArrayList<CancelPolicy> CancelPolicy = new ArrayList<CancelPolicy>();

    public ArrayList<String> TextPolicy = new ArrayList<String>();

    public ArrayList<CancelPolicy> NoShowPolicy = new ArrayList<CancelPolicy>();
    
    public String DefaultPolicy;

    public String AutoCancellationText;

    public Enums.PolicyFormat PolicyFormat = Enums.PolicyFormat.Text;
    private transient java.lang.Object __source;


    public void loadFromSoap(java.lang.Object paramObj, ExtendedSoapSerializationEnvelope __envelope) {
        if (paramObj == null)
            return;
        AttributeContainer inObj = (AttributeContainer) paramObj;
        __source = inObj;
        if (inObj instanceof SoapObject) {
            SoapObject soapObject = (SoapObject) inObj;
            int size = soapObject.getPropertyCount();
            for (int i0 = 0; i0 < size; i0++) {
                PropertyInfo info = soapObject.getPropertyInfo(i0);
                if (!loadProperty(info, soapObject, __envelope)) {
                }
            } 
        }
        if (inObj.hasAttribute("PolicyFormat")) {
            java.lang.Object j = inObj.getAttribute("PolicyFormat");
            if (j != null) {
                PolicyFormat = Enums.PolicyFormat.fromString(j.toString());
            }
        }

    }


    protected boolean loadProperty(PropertyInfo info, SoapObject soapObject, ExtendedSoapSerializationEnvelope __envelope) {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("LastCancellationDeadline")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.LastCancellationDeadline = Helper.ConvertFromWebService(j.toString());
                    }
                } else if (obj instanceof org.joda.time.DateTime) {
                    this.LastCancellationDeadline = (org.joda.time.DateTime) obj;
                }
            }
            return true;
        }
        if (info.name.equals("CancelPolicy")) {
            if (obj != null) {
                if (this.CancelPolicy == null) {
                    this.CancelPolicy = new java.util.ArrayList<CancelPolicy>();
                }
                java.lang.Object j = obj;
                CancelPolicy j1 = (CancelPolicy) __envelope.get(j, CancelPolicy.class, false);
                this.CancelPolicy.add(j1);
            }
            return true;
        }
        if (info.name.equals("TextPolicy")) {
            if (obj != null) {
                if (this.TextPolicy == null) {
                    this.TextPolicy = new java.util.ArrayList<String>();
                }
                java.lang.Object j = obj;
                String j1 = j.toString();
                this.TextPolicy.add(j1);
            }
            return true;
        }
        if (info.name.equals("NoShowPolicy")) {
            if (obj != null) {
                if (this.NoShowPolicy == null) {
                    this.NoShowPolicy = new java.util.ArrayList<CancelPolicy>();
                }
                java.lang.Object j = obj;
                CancelPolicy j1 = (CancelPolicy) __envelope.get(j, CancelPolicy.class, false);
                this.NoShowPolicy.add(j1);
            }
            return true;
        }
        if (info.name.equals("DefaultPolicy")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.DefaultPolicy = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.DefaultPolicy = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("AutoCancellationText")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.AutoCancellationText = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.AutoCancellationText = (String) obj;
                }
            }
            return true;
        }
        return false;
    }

    public java.lang.Object getOriginalXmlSource() {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if (propertyIndex == 0) {
            return this.LastCancellationDeadline != null ? this.LastCancellationDeadline.toString() : SoapPrimitive.NullNilElement;
        }
        if (propertyIndex >= 1 && propertyIndex < 1 + this.CancelPolicy.size()) {
            java.lang.Object CancelPolicy = this.CancelPolicy.get(propertyIndex - (1));
            return CancelPolicy != null ? CancelPolicy : SoapPrimitive.NullNilElement;
        }
        if (propertyIndex >= 1 + this.CancelPolicy.size() && propertyIndex < 1 + this.CancelPolicy.size() + this.TextPolicy.size()) {
            java.lang.Object TextPolicy = this.TextPolicy.get(propertyIndex - (1 + this.CancelPolicy.size()));
            return TextPolicy != null ? TextPolicy : SoapPrimitive.NullNilElement;
        }
        if (propertyIndex >= 1 + this.CancelPolicy.size() + this.TextPolicy.size() && propertyIndex < 1 + this.CancelPolicy.size() + this.TextPolicy.size() + this.NoShowPolicy.size()) {
            java.lang.Object NoShowPolicy = this.NoShowPolicy.get(propertyIndex - (1 + this.CancelPolicy.size() + this.TextPolicy.size()));
            return NoShowPolicy != null ? NoShowPolicy : SoapPrimitive.NullNilElement;
        }
        if (propertyIndex == 1 + this.CancelPolicy.size() + this.TextPolicy.size() + this.NoShowPolicy.size()) {
            return this.DefaultPolicy != null ? this.DefaultPolicy : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 2 + this.CancelPolicy.size() + this.TextPolicy.size() + this.NoShowPolicy.size()) {
            return this.AutoCancellationText != null ? this.AutoCancellationText : SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 3 + CancelPolicy.size() + TextPolicy.size() + NoShowPolicy.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        if (propertyIndex == 0) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "LastCancellationDeadline";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex >= 1 && propertyIndex < 1 + this.CancelPolicy.size()) {
            info.type = CancelPolicy.class;
            info.name = "CancelPolicy";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex >= 1 + this.CancelPolicy.size() && propertyIndex < 1 + this.CancelPolicy.size() + this.TextPolicy.size()) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TextPolicy";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex >= 1 + this.CancelPolicy.size() + this.TextPolicy.size() && propertyIndex < 1 + this.CancelPolicy.size() + this.TextPolicy.size() + this.NoShowPolicy.size()) {
            info.type = CancelPolicy.class;
            info.name = "NoShowPolicy";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 1 + this.CancelPolicy.size() + this.TextPolicy.size() + this.NoShowPolicy.size()) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DefaultPolicy";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 2 + this.CancelPolicy.size() + this.TextPolicy.size() + this.NoShowPolicy.size()) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "AutoCancellationText";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1) {
    }



    @Override
    public int getAttributeCount() {
        return 1;
    }

    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if (index == 0) {
            info.name = "PolicyFormat";
            info.namespace = "";
            if (this.PolicyFormat != null) {
                info.setValue(this.PolicyFormat);
            }

        }
    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }    
}

