package com.Tamm.Hotels.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.5.5
//
// Created by Quasar Development 
//
//---------------------------------------------------


import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.AttributeInfo;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;

import java.math.BigDecimal;
import java.util.Hashtable;

public class CancelPolicy extends AttributeContainer implements KvmSerializable {


    public String RoomTypeName;

    public String RoomIndex;

    public String FromDate;

    public String ToDate;

    public Enums.CancellationChargeTypeForHotel ChargeType = Enums.CancellationChargeTypeForHotel.Fixed;

    public BigDecimal CancellationCharge = BigDecimal.ZERO;

    public String Currency;

    public String PrefCurrency;

    public String PrefCancellationCharge;
    private transient java.lang.Object __source;


    public void loadFromSoap(java.lang.Object paramObj, ExtendedSoapSerializationEnvelope __envelope) {
        if (paramObj == null)
            return;
        AttributeContainer inObj = (AttributeContainer) paramObj;
        __source = inObj;
        if (inObj instanceof SoapObject) {
            SoapObject soapObject = (SoapObject) inObj;
            int size = soapObject.getPropertyCount();
            for (int i0 = 0; i0 < size; i0++) {
                PropertyInfo info = soapObject.getPropertyInfo(i0);
                if (!loadProperty(info, soapObject, __envelope)) {
                }
            }
        }
        if (inObj.hasAttribute("RoomTypeName")) {
            java.lang.Object j = inObj.getAttribute("RoomTypeName");
            if (j != null) {
                RoomTypeName = j.toString();
            }
        }
        if (inObj.hasAttribute("RoomIndex")) {
            java.lang.Object j = inObj.getAttribute("RoomIndex");
            if (j != null) {
                RoomIndex = j.toString();
            }
        }
        if (inObj.hasAttribute("FromDate")) {
            java.lang.Object j = inObj.getAttribute("FromDate");
            if (j != null) {
                FromDate = j.toString();
            }
        }
        if (inObj.hasAttribute("ToDate")) {
            java.lang.Object j = inObj.getAttribute("ToDate");
            if (j != null) {
                ToDate = j.toString();
            }
        }
        if (inObj.hasAttribute("ChargeType")) {
            java.lang.Object j = inObj.getAttribute("ChargeType");
            if (j != null) {
                ChargeType = Enums.CancellationChargeTypeForHotel.fromString(j.toString());
            }
        }
        if (inObj.hasAttribute("CancellationCharge")) {
            java.lang.Object j = inObj.getAttribute("CancellationCharge");
            if (j != null) {
                CancellationCharge = new BigDecimal(j.toString());
            }
        }
        if (inObj.hasAttribute("Currency")) {
            java.lang.Object j = inObj.getAttribute("Currency");
            if (j != null) {
                Currency = j.toString();
            }
        }
        if (inObj.hasAttribute("PrefCurrency")) {
            java.lang.Object j = inObj.getAttribute("PrefCurrency");
            if (j != null) {
                PrefCurrency = j.toString();
            }
        }
        if (inObj.hasAttribute("PrefCancellationCharge")) {
            java.lang.Object j = inObj.getAttribute("PrefCancellationCharge");
            if (j != null) {
                PrefCancellationCharge = j.toString();
            }
        }

    }


    protected boolean loadProperty(PropertyInfo info, SoapObject soapObject, ExtendedSoapSerializationEnvelope __envelope) {
        java.lang.Object obj = info.getValue();
        return false;
    }

    public java.lang.Object getOriginalXmlSource() {
        return __source;
    }


    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 0;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1) {
    }


    @Override
    public int getAttributeCount() {
        return 9;
    }

    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if (index == 0) {
            info.name = "RoomTypeName";
            info.namespace = "";
            if (this.RoomTypeName != null) {
                info.setValue(this.RoomTypeName);
            }

        }
        if (index == 1) {
            info.name = "RoomIndex";
            info.namespace = "";
            if (this.RoomIndex != null) {
                info.setValue(this.RoomIndex);
            }

        }
        if (index == 2) {
            info.name = "FromDate";
            info.namespace = "";
            if (this.FromDate != null) {
                info.setValue(this.FromDate);
            }

        }
        if (index == 3) {
            info.name = "ToDate";
            info.namespace = "";
            if (this.ToDate != null) {
                info.setValue(this.ToDate);
            }

        }
        if (index == 4) {
            info.name = "ChargeType";
            info.namespace = "";
            if (this.ChargeType != null) {
                info.setValue(this.ChargeType);
            }

        }
        if (index == 5) {
            info.name = "CancellationCharge";
            info.namespace = "";
            if (this.CancellationCharge != null) {
                info.setValue(this.CancellationCharge);
            }

        }
        if (index == 6) {
            info.name = "Currency";
            info.namespace = "";
            if (this.Currency != null) {
                info.setValue(this.Currency);
            }

        }
        if (index == 7) {
            info.name = "PrefCurrency";
            info.namespace = "";
            if (this.PrefCurrency != null) {
                info.setValue(this.PrefCurrency);
            }

        }
        if (index == 8) {
            info.name = "PrefCancellationCharge";
            info.namespace = "";
            if (this.PrefCancellationCharge != null) {
                info.setValue(this.PrefCancellationCharge);
            }

        }
    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }
}

