package com.Tamm.Hotels.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.5.5
//
// Created by Quasar Development 
//
//---------------------------------------------------


import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.math.BigDecimal;
import java.util.Hashtable;

public class HotelInfo extends AttributeContainer implements KvmSerializable {


    public String HotelCode;

    public String HotelName;

    public String HotelPicture;

    public String HotelDescription;

    public BigDecimal Latitude;

    public BigDecimal Longitude;

    public String HotelAddress;

    public String HotelContactNo;

    public Enums.HotelInfoHotelRating Rating = Enums.HotelInfoHotelRating.All;

    public String HotelPromotion;

    public String TripAdvisorRating;

    public String TripAdvisorReviewURL;

    public String TagIds;
    private transient java.lang.Object __source;


    public void loadFromSoap(java.lang.Object paramObj, ExtendedSoapSerializationEnvelope __envelope) {
        if (paramObj == null)
            return;
        AttributeContainer inObj = (AttributeContainer) paramObj;
        __source = inObj;
        if (inObj instanceof SoapObject) {
            SoapObject soapObject = (SoapObject) inObj;
            int size = soapObject.getPropertyCount();
            for (int i0 = 0; i0 < size; i0++) {
                PropertyInfo info = soapObject.getPropertyInfo(i0);
                if (!loadProperty(info, soapObject, __envelope)) {
                }
            }
        }

    }


    protected boolean loadProperty(PropertyInfo info, SoapObject soapObject, ExtendedSoapSerializationEnvelope __envelope) {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("HotelCode")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.HotelCode = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.HotelCode = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("HotelName")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.HotelName = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.HotelName = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("HotelPicture")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.HotelPicture = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.HotelPicture = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("HotelDescription")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.HotelDescription = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.HotelDescription = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("Latitude")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.Latitude = new BigDecimal(j.toString());
                    }
                } else if (obj instanceof BigDecimal) {
                    this.Latitude = (BigDecimal) obj;
                }
            }
            return true;
        }
        if (info.name.equals("Longitude")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.Longitude = new BigDecimal(j.toString());
                    }
                } else if (obj instanceof BigDecimal) {
                    this.Longitude = (BigDecimal) obj;
                }
            }
            return true;
        }
        if (info.name.equals("HotelAddress")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.HotelAddress = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.HotelAddress = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("HotelContactNo")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.HotelContactNo = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.HotelContactNo = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("Rating")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.Rating = Enums.HotelInfoHotelRating.fromString(j.toString());
                    }
                } else if (obj instanceof Enums.HotelInfoHotelRating) {
                    this.Rating = (Enums.HotelInfoHotelRating) obj;
                }
            }
            return true;
        }
        if (info.name.equals("HotelPromotion")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.HotelPromotion = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.HotelPromotion = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("TripAdvisorRating")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.TripAdvisorRating = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.TripAdvisorRating = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("TripAdvisorReviewURL")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.TripAdvisorReviewURL = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.TripAdvisorReviewURL = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("TagIds")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.TagIds = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.TagIds = (String) obj;
                }
            }
            return true;
        }
        return false;
    }

    public java.lang.Object getOriginalXmlSource() {
        return __source;
    }


    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if (propertyIndex == 0) {
            return this.HotelCode != null ? this.HotelCode : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 1) {
            return this.HotelName != null ? this.HotelName : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 2) {
            return this.HotelPicture != null ? this.HotelPicture : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 3) {
            return this.HotelDescription != null ? this.HotelDescription : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 4) {
            return this.Latitude != null ? this.Latitude.toString() : SoapPrimitive.NullNilElement;
        }
        if (propertyIndex == 5) {
            return this.Longitude != null ? this.Longitude.toString() : SoapPrimitive.NullNilElement;
        }
        if (propertyIndex == 6) {
            return this.HotelAddress != null ? this.HotelAddress : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 7) {
            return this.HotelContactNo != null ? this.HotelContactNo : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 8) {
            return this.Rating != null ? this.Rating.toString() : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 9) {
            return this.HotelPromotion != null ? this.HotelPromotion : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 10) {
            return this.TripAdvisorRating != null ? this.TripAdvisorRating : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 11) {
            return this.TripAdvisorReviewURL != null ? this.TripAdvisorReviewURL : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 12) {
            return this.TagIds != null ? this.TagIds : SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 13;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        if (propertyIndex == 0) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "HotelCode";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 1) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "HotelName";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 2) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "HotelPicture";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 3) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "HotelDescription";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 4) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Latitude";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 5) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Longitude";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 6) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "HotelAddress";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 7) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "HotelContactNo";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 8) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Rating";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 9) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "HotelPromotion";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 10) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TripAdvisorRating";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 11) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TripAdvisorReviewURL";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 12) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TagIds";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1) {
    }


}

