package com.Tamm.Hotels.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.6.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class HotelSearchWithRoomsResponse extends AttributeContainer implements KvmSerializable {

    
    public ResponseStatus Status;

    public String ResponseTime;

    public String Language;

    public String SessionId;

    public String NoOfRoomsRequested;

    public String CityId;

    public String CheckInDate;

    public String CheckOutDate;

    public ArrayOfRoomGuest RoomGuests;

    public ArrayOfHotel_ResultWithRooms HotelResultList;
    private transient java.lang.Object __source;


    public void loadFromSoap(java.lang.Object paramObj, ExtendedSoapSerializationEnvelope __envelope) {
        if (paramObj == null)
            return;
        AttributeContainer inObj = (AttributeContainer) paramObj;
        __source = inObj;
        if (inObj instanceof SoapObject) {
            SoapObject soapObject = (SoapObject) inObj;
            int size = soapObject.getPropertyCount();
            for (int i0 = 0; i0 < size; i0++) {
                PropertyInfo info = soapObject.getPropertyInfo(i0);
                if (!loadProperty(info, soapObject, __envelope)) {
                }
            } 
        }

    }


    protected boolean loadProperty(PropertyInfo info, SoapObject soapObject, ExtendedSoapSerializationEnvelope __envelope) {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("Status")) {
            if (obj != null) {
                java.lang.Object j = obj;
                this.Status = (ResponseStatus) __envelope.get(j, ResponseStatus.class, false);
            }
            return true;
        }
        if (info.name.equals("ResponseTime")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.ResponseTime = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.ResponseTime = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("Language")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.Language = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.Language = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("SessionId")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.SessionId = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.SessionId = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("NoOfRoomsRequested")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.NoOfRoomsRequested = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.NoOfRoomsRequested = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("CityId")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.CityId = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.CityId = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("CheckInDate")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.CheckInDate = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.CheckInDate = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("CheckOutDate")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.CheckOutDate = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.CheckOutDate = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("RoomGuests")) {
            if (obj != null) {
                java.lang.Object j = obj;
                this.RoomGuests = (ArrayOfRoomGuest) __envelope.get(j, ArrayOfRoomGuest.class, false);
            }
            return true;
        }
        if (info.name.equals("HotelResultList")) {
            if (obj != null) {
                java.lang.Object j = obj;
                this.HotelResultList = (ArrayOfHotel_ResultWithRooms) __envelope.get(j, ArrayOfHotel_ResultWithRooms.class, false);
            }
            return true;
        }
        return false;
    }

    public java.lang.Object getOriginalXmlSource() {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if (propertyIndex == 0) {
            return this.Status != null ? this.Status : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 1) {
            return this.ResponseTime != null ? this.ResponseTime : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 2) {
            return this.Language != null ? this.Language : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 3) {
            return this.SessionId != null ? this.SessionId : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 4) {
            return this.NoOfRoomsRequested != null ? this.NoOfRoomsRequested : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 5) {
            return this.CityId != null ? this.CityId : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 6) {
            return this.CheckInDate != null ? this.CheckInDate : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 7) {
            return this.CheckOutDate != null ? this.CheckOutDate : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 8) {
            return this.RoomGuests != null ? this.RoomGuests : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 9) {
            return this.HotelResultList != null ? this.HotelResultList : SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 10;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        if (propertyIndex == 0) {
            info.type = ResponseStatus.class;
            info.name = "Status";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 1) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ResponseTime";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 2) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Language";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 3) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SessionId";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 4) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "NoOfRoomsRequested";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 5) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CityId";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 6) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CheckInDate";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 7) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CheckOutDate";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 8) {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "RoomGuests";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 9) {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "HotelResultList";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1) {
    }


}

