package com.Tamm.Hotels.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.6.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class HotelBookResponse extends AttributeContainer implements KvmSerializable {

    
    public ResponseStatus Status;

    public Enums.APIHotelBookingStatus BookingStatus = Enums.APIHotelBookingStatus.Failed;

    public Integer BookingId = 0;
    
    public String ConfirmationNo;

    public Integer TripId = 0;
    
    public String SupplierReferenceNo;

    public PriceChangeStatus PriceChange;


    public String SupplierConfirmationNo;
    private transient java.lang.Object __source;


    public void loadFromSoap(java.lang.Object paramObj, ExtendedSoapSerializationEnvelope __envelope) {
        if (paramObj == null)
            return;
        AttributeContainer inObj = (AttributeContainer) paramObj;
        __source = inObj;
        if (inObj instanceof SoapObject) {
            SoapObject soapObject = (SoapObject) inObj;
            int size = soapObject.getPropertyCount();
            for (int i0 = 0; i0 < size; i0++) {
                PropertyInfo info = soapObject.getPropertyInfo(i0);
                if (!loadProperty(info, soapObject, __envelope)) {
                }
            } 
        }

    }


    protected boolean loadProperty(PropertyInfo info, SoapObject soapObject, ExtendedSoapSerializationEnvelope __envelope) {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("Status")) {
            if (obj != null) {
                java.lang.Object j = obj;
                this.Status = (ResponseStatus) __envelope.get(j, ResponseStatus.class, false);
            }
            return true;
        }
        if (info.name.equals("BookingStatus")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.BookingStatus = Enums.APIHotelBookingStatus.fromString(j.toString());
                    }
                } else if (obj instanceof Enums.APIHotelBookingStatus) {
                    this.BookingStatus = (Enums.APIHotelBookingStatus) obj;
                }
            }
            return true;
        }
        if (info.name.equals("BookingId")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.BookingId = Integer.parseInt(j.toString());
                    }
                } else if (obj instanceof Integer) {
                    this.BookingId = (Integer) obj;
                }
            }
            return true;
        }
        if (info.name.equals("ConfirmationNo")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.ConfirmationNo = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.ConfirmationNo = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("TripId")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.TripId = Integer.parseInt(j.toString());
                    }
                } else if (obj instanceof Integer) {
                    this.TripId = (Integer) obj;
                }
            }
            return true;
        }
        if (info.name.equals("SupplierReferenceNo")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.SupplierReferenceNo = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.SupplierReferenceNo = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("PriceChange")) {
            if (obj != null) {
                java.lang.Object j = obj;
                this.PriceChange = (PriceChangeStatus) __envelope.get(j, PriceChangeStatus.class, false);
            }
            return true;
        }
        if (info.name.equals("SupplierConfirmationNo")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.SupplierConfirmationNo = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.SupplierConfirmationNo = (String) obj;
                }
            }
            return true;
        }
        return false;
    }

    public java.lang.Object getOriginalXmlSource() {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if (propertyIndex == 0) {
            return this.Status != null ? this.Status : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 1) {
            return this.BookingStatus != null ? this.BookingStatus.toString() : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 2) {
            return BookingId;
        }
        if (propertyIndex == 3) {
            return this.ConfirmationNo != null ? this.ConfirmationNo : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 4) {
            return TripId;
        }
        if (propertyIndex == 5) {
            return this.SupplierReferenceNo != null ? this.SupplierReferenceNo : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 6) {
            return this.PriceChange != null ? this.PriceChange : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 7) {
            return this.SupplierConfirmationNo != null ? this.SupplierConfirmationNo : SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 8;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        if (propertyIndex == 0) {
            info.type = ResponseStatus.class;
            info.name = "Status";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 1) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "BookingStatus";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 2) {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "BookingId";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 3) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ConfirmationNo";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 4) {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "TripId";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 5) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SupplierReferenceNo";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 6) {
            info.type = PriceChangeStatus.class;
            info.name = "PriceChange";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 7) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SupplierConfirmationNo";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1) {
    }


}

