package com.Tamm.Hotels.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.6.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.math.BigDecimal;
import java.util.Hashtable;

public class HotelCancelResponse extends AttributeContainer implements KvmSerializable {

    
    public ResponseStatus Status;

    public Integer BookingId = 0;

    public BigDecimal CancellationCharge = BigDecimal.ZERO;

    public BigDecimal RefundAmount = BigDecimal.ZERO;

    public Enums.HotelCancelStatus RequestStatus = Enums.HotelCancelStatus.UnProcessed;
    
    public String Currency;
    private transient java.lang.Object __source;


    public void loadFromSoap(java.lang.Object paramObj, ExtendedSoapSerializationEnvelope __envelope) {
        if (paramObj == null)
            return;
        AttributeContainer inObj = (AttributeContainer) paramObj;
        __source = inObj;
        if (inObj instanceof SoapObject) {
            SoapObject soapObject = (SoapObject) inObj;
            int size = soapObject.getPropertyCount();
            for (int i0 = 0; i0 < size; i0++) {
                PropertyInfo info = soapObject.getPropertyInfo(i0);
                if (!loadProperty(info, soapObject, __envelope)) {
                }
            } 
        }

    }


    protected boolean loadProperty(PropertyInfo info, SoapObject soapObject, ExtendedSoapSerializationEnvelope __envelope) {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("Status")) {
            if (obj != null) {
                java.lang.Object j = obj;
                this.Status = (ResponseStatus) __envelope.get(j, ResponseStatus.class, false);
            }
            return true;
        }
        if (info.name.equals("BookingId")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.BookingId = Integer.parseInt(j.toString());
                    }
                } else if (obj instanceof Integer) {
                    this.BookingId = (Integer) obj;
                }
            }
            return true;
        }
        if (info.name.equals("CancellationCharge")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.CancellationCharge = new BigDecimal(j.toString());
                    }
                } else if (obj instanceof BigDecimal) {
                    this.CancellationCharge = (BigDecimal) obj;
                }
            }
            return true;
        }
        if (info.name.equals("RefundAmount")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.RefundAmount = new BigDecimal(j.toString());
                    }
                } else if (obj instanceof BigDecimal) {
                    this.RefundAmount = (BigDecimal) obj;
                }
            }
            return true;
        }
        if (info.name.equals("RequestStatus")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.RequestStatus = Enums.HotelCancelStatus.fromString(j.toString());
                    }
                } else if (obj instanceof Enums.HotelCancelStatus) {
                    this.RequestStatus = (Enums.HotelCancelStatus) obj;
                }
            }
            return true;
        }
        if (info.name.equals("Currency")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.Currency = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.Currency = (String) obj;
                }
            }
            return true;
        }
        return false;
    }

    public java.lang.Object getOriginalXmlSource() {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if (propertyIndex == 0) {
            return this.Status != null ? this.Status : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 1) {
            return BookingId;
        }
        if (propertyIndex == 2) {
            return this.CancellationCharge != null ? this.CancellationCharge.toString() : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 3) {
            return this.RefundAmount != null ? this.RefundAmount.toString() : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 4) {
            return this.RequestStatus != null ? this.RequestStatus.toString() : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 5) {
            return this.Currency != null ? this.Currency : SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 6;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        if (propertyIndex == 0) {
            info.type = ResponseStatus.class;
            info.name = "Status";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 1) {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "BookingId";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 2) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CancellationCharge";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 3) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "RefundAmount";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 4) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "RequestStatus";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 5) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Currency";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1) {
    }


}

