package com.Tamm.Hotels.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.6.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.AttributeInfo;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class ImageUrlDetails {

    
    public String value;

    public String CategoryId;

    public String CategoryName;
    private transient java.lang.Object __source;


    public void loadFromSoap(java.lang.Object paramObj, ExtendedSoapSerializationEnvelope __envelope) {
        if (paramObj == null)
            return;
        AttributeContainer inObj = (AttributeContainer) paramObj;
        __source = inObj;
        if (!(inObj instanceof SoapObject)) {
            java.lang.Object j = inObj;
            value = j.toString();
        }
        if (inObj.hasAttribute("CategoryId")) {
            java.lang.Object j = inObj.getAttribute("CategoryId");
            if (j != null) {
                CategoryId = j.toString();
            }
        }
        if (inObj.hasAttribute("CategoryName")) {
            java.lang.Object j = inObj.getAttribute("CategoryName");
            if (j != null) {
                CategoryName = j.toString();
            }
        }

    }


    protected boolean loadProperty(PropertyInfo info, SoapObject soapObject, ExtendedSoapSerializationEnvelope __envelope) {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("value")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.value = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.value = (String) obj;
                }
            }
            return true;
        }
        return false;
    }

    public java.lang.Object getOriginalXmlSource() {
        return __source;
    }

    public Object getSimpleValue() {
        Object value = this.value != null ? this.value : "";
        SoapPrimitive primitive = new SoapPrimitive("http://TekTravel/HotelBookingApi", "value", value);

        if (this.CategoryId != null) {
            AttributeInfo attrInfo = new AttributeInfo();
            attrInfo.setName("CategoryId");
            attrInfo.setValue(this.CategoryId);
            attrInfo.setNamespace("");
            primitive.addAttribute(attrInfo);
        }
        if (this.CategoryName != null) {
            AttributeInfo attrInfo = new AttributeInfo();
            attrInfo.setName("CategoryName");
            attrInfo.setValue(this.CategoryName);
            attrInfo.setNamespace("");
            primitive.addAttribute(attrInfo);
        }
        return primitive;
    }    
}

