package com.Tamm.Hotels.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.6.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.AttributeInfo;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;

import java.math.BigDecimal;
import java.util.Hashtable;

public class Rate extends AttributeContainer implements KvmSerializable {


    public BigDecimal RoomFare = BigDecimal.ZERO;

    public BigDecimal RoomTax = BigDecimal.ZERO;

    public BigDecimal TotalFare = BigDecimal.ZERO;
    private transient java.lang.Object __source;


    public void loadFromSoap(java.lang.Object paramObj, ExtendedSoapSerializationEnvelope __envelope) {
        if (paramObj == null)
            return;
        AttributeContainer inObj = (AttributeContainer) paramObj;
        __source = inObj;
        if (inObj instanceof SoapObject) {
            SoapObject soapObject = (SoapObject) inObj;
            int size = soapObject.getPropertyCount();
            for (int i0 = 0; i0 < size; i0++) {
                PropertyInfo info = soapObject.getPropertyInfo(i0);
                if (!loadProperty(info, soapObject, __envelope)) {
                }
            } 
        }
        if (inObj.hasAttribute("RoomFare")) {
            java.lang.Object j = inObj.getAttribute("RoomFare");
            if (j != null) {
                RoomFare = new BigDecimal(j.toString());
            }
        }
        if (inObj.hasAttribute("RoomTax")) {
            java.lang.Object j = inObj.getAttribute("RoomTax");
            if (j != null) {
                RoomTax = new BigDecimal(j.toString());
            }
        }
        if (inObj.hasAttribute("TotalFare")) {
            java.lang.Object j = inObj.getAttribute("TotalFare");
            if (j != null) {
                TotalFare = new BigDecimal(j.toString());
            }
        }

    }


    protected boolean loadProperty(PropertyInfo info, SoapObject soapObject, ExtendedSoapSerializationEnvelope __envelope) {
        java.lang.Object obj = info.getValue();
        return false;
    }

    public java.lang.Object getOriginalXmlSource() {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 0;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1) {
    }



    @Override
    public int getAttributeCount() {
        return 3;
    }

    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if (index == 0) {
            info.name = "RoomFare";
            info.namespace = "";
            if (this.RoomFare != null) {
                info.setValue(this.RoomFare);
            }

        }
        if (index == 1) {
            info.name = "RoomTax";
            info.namespace = "";
            if (this.RoomTax != null) {
                info.setValue(this.RoomTax);
            }

        }
        if (index == 2) {
            info.name = "TotalFare";
            info.namespace = "";
            if (this.TotalFare != null) {
                info.setValue(this.TotalFare);
            }

        }
    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }    
}

