package com.Tamm.Hotels.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.5.5
//
// Created by Quasar Development 
//
//---------------------------------------------------


import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.ArrayList;
import java.util.Hashtable;

public class RoomCombination extends AttributeContainer implements KvmSerializable {


    public ArrayList<Integer> RoomIndex = new ArrayList<Integer>();

    public String TestElement;
    private transient java.lang.Object __source;


    public void loadFromSoap(java.lang.Object paramObj, ExtendedSoapSerializationEnvelope __envelope) {
        if (paramObj == null)
            return;
        AttributeContainer inObj = (AttributeContainer) paramObj;
        __source = inObj;
        if (inObj instanceof SoapObject) {
            SoapObject soapObject = (SoapObject) inObj;
            int size = soapObject.getPropertyCount();
            for (int i0 = 0; i0 < size; i0++) {
                PropertyInfo info = soapObject.getPropertyInfo(i0);
                if (!loadProperty(info, soapObject, __envelope)) {
                }
            }
        }

    }


    protected boolean loadProperty(PropertyInfo info, SoapObject soapObject, ExtendedSoapSerializationEnvelope __envelope) {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("RoomIndex")) {
            if (obj != null) {
                if (this.RoomIndex == null) {
                    this.RoomIndex = new java.util.ArrayList<Integer>();
                }
                java.lang.Object j = obj;
                Integer j1 = Integer.parseInt(j.toString());
                this.RoomIndex.add(j1);
            }
            return true;
        }
        if (info.name.equals("TestElement")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.TestElement = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.TestElement = (String) obj;
                }
            }
            return true;
        }
        return false;
    }

    public java.lang.Object getOriginalXmlSource() {
        return __source;
    }


    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if (propertyIndex >= 0 && propertyIndex < 0 + this.RoomIndex.size()) {
            java.lang.Object RoomIndex = this.RoomIndex.get(propertyIndex - (0));
            return RoomIndex != null ? RoomIndex : SoapPrimitive.NullNilElement;
        }
        if (propertyIndex == 0 + this.RoomIndex.size()) {
            return this.TestElement != null ? this.TestElement : SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 1 + RoomIndex.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        if (propertyIndex >= 0 && propertyIndex < 0 + this.RoomIndex.size()) {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "RoomIndex";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 0 + this.RoomIndex.size()) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TestElement";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1) {
    }


}

