package com.Tamm.Hotels.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.6.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.AttributeInfo;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.math.BigDecimal;
import java.util.Hashtable;

public class RoomRate extends AttributeContainer implements KvmSerializable {

    
    public ArrayOfDayRate DayRates;

    public BigDecimal ExtraGuestCharges = BigDecimal.ZERO;

    public BigDecimal ChildCharges = BigDecimal.ZERO;

    public BigDecimal Discount = BigDecimal.ZERO;

    public BigDecimal OtherCharges = BigDecimal.ZERO;

    public BigDecimal ServiceTax = BigDecimal.ZERO;

    public Boolean IsPackageRate = false;

    public Boolean B2CRates = false;

    public BigDecimal AgentMarkUp = BigDecimal.ZERO;
    
    public String Currency;

    public BigDecimal RoomFare = BigDecimal.ZERO;

    public BigDecimal RoomTax = BigDecimal.ZERO;
    
    public String PrefPrice;

    public String HeadGSAMarkUp;

    public BigDecimal TotalFare = BigDecimal.ZERO;
    
    public String PrefCurrency;
    private transient java.lang.Object __source;


    public void loadFromSoap(java.lang.Object paramObj, ExtendedSoapSerializationEnvelope __envelope) {
        if (paramObj == null)
            return;
        AttributeContainer inObj = (AttributeContainer) paramObj;
        __source = inObj;
        if (inObj instanceof SoapObject) {
            SoapObject soapObject = (SoapObject) inObj;
            int size = soapObject.getPropertyCount();
            for (int i0 = 0; i0 < size; i0++) {
                PropertyInfo info = soapObject.getPropertyInfo(i0);
                if (!loadProperty(info, soapObject, __envelope)) {
                }
            } 
        }
        if (inObj.hasAttribute("IsPackageRate")) {
            java.lang.Object j = inObj.getAttribute("IsPackageRate");
            if (j != null) {
                IsPackageRate = new Boolean(j.toString());
            }
        }
        if (inObj.hasAttribute("B2CRates")) {
            java.lang.Object j = inObj.getAttribute("B2CRates");
            if (j != null) {
                B2CRates = new Boolean(j.toString());
            }
        }
        if (inObj.hasAttribute("AgentMarkUp")) {
            java.lang.Object j = inObj.getAttribute("AgentMarkUp");
            if (j != null) {
                AgentMarkUp = new BigDecimal(j.toString());
            }
        }
        if (inObj.hasAttribute("Currency")) {
            java.lang.Object j = inObj.getAttribute("Currency");
            if (j != null) {
                Currency = j.toString();
            }
        }
        if (inObj.hasAttribute("RoomFare")) {
            java.lang.Object j = inObj.getAttribute("RoomFare");
            if (j != null) {
                RoomFare = new BigDecimal(j.toString());
            }
        }
        if (inObj.hasAttribute("RoomTax")) {
            java.lang.Object j = inObj.getAttribute("RoomTax");
            if (j != null) {
                RoomTax = new BigDecimal(j.toString());
            }
        }
        if (inObj.hasAttribute("PrefPrice")) {
            java.lang.Object j = inObj.getAttribute("PrefPrice");
            if (j != null) {
                PrefPrice = j.toString();
            }
        }
        if (inObj.hasAttribute("HeadGSAMarkUp")) {
            java.lang.Object j = inObj.getAttribute("HeadGSAMarkUp");
            if (j != null) {
                HeadGSAMarkUp = j.toString();
            }
        }
        if (inObj.hasAttribute("TotalFare")) {
            java.lang.Object j = inObj.getAttribute("TotalFare");
            if (j != null) {
                TotalFare = new BigDecimal(j.toString());
            }
        }
        if (inObj.hasAttribute("PrefCurrency")) {
            java.lang.Object j = inObj.getAttribute("PrefCurrency");
            if (j != null) {
                PrefCurrency = j.toString();
            }
        }

    }


    protected boolean loadProperty(PropertyInfo info, SoapObject soapObject, ExtendedSoapSerializationEnvelope __envelope) {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("DayRates")) {
            if (obj != null) {
                java.lang.Object j = obj;
                this.DayRates = (ArrayOfDayRate) __envelope.get(j, ArrayOfDayRate.class, false);
            }
            return true;
        }
        if (info.name.equals("ExtraGuestCharges")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.ExtraGuestCharges = new BigDecimal(j.toString());
                    }
                } else if (obj instanceof BigDecimal) {
                    this.ExtraGuestCharges = (BigDecimal) obj;
                }
            }
            return true;
        }
        if (info.name.equals("ChildCharges")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.ChildCharges = new BigDecimal(j.toString());
                    }
                } else if (obj instanceof BigDecimal) {
                    this.ChildCharges = (BigDecimal) obj;
                }
            }
            return true;
        }
        if (info.name.equals("Discount")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.Discount = new BigDecimal(j.toString());
                    }
                } else if (obj instanceof BigDecimal) {
                    this.Discount = (BigDecimal) obj;
                }
            }
            return true;
        }
        if (info.name.equals("OtherCharges")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.OtherCharges = new BigDecimal(j.toString());
                    }
                } else if (obj instanceof BigDecimal) {
                    this.OtherCharges = (BigDecimal) obj;
                }
            }
            return true;
        }
        if (info.name.equals("ServiceTax")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.ServiceTax = new BigDecimal(j.toString());
                    }
                } else if (obj instanceof BigDecimal) {
                    this.ServiceTax = (BigDecimal) obj;
                }
            }
            return true;
        }
        return false;
    }

    public java.lang.Object getOriginalXmlSource() {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if (propertyIndex == 0) {
            return this.DayRates != null ? this.DayRates : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 1) {
            return this.ExtraGuestCharges != null ? this.ExtraGuestCharges.toString() : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 2) {
            return this.ChildCharges != null ? this.ChildCharges.toString() : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 3) {
            return this.Discount != null ? this.Discount.toString() : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 4) {
            return this.OtherCharges != null ? this.OtherCharges.toString() : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 5) {
            return this.ServiceTax != null ? this.ServiceTax.toString() : SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 6;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        if (propertyIndex == 0) {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "DayRates";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 1) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ExtraGuestCharges";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 2) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ChildCharges";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 3) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Discount";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 4) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "OtherCharges";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
        if (propertyIndex == 5) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ServiceTax";
            info.namespace = "http://TekTravel/HotelBookingApi";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1) {
    }



    @Override
    public int getAttributeCount() {
        return 10;
    }

    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if (index == 0) {
            info.name = "IsPackageRate";
            info.namespace = "";
            if (this.IsPackageRate != null) {
                info.setValue(this.IsPackageRate);
            }

        }
        if (index == 1) {
            info.name = "B2CRates";
            info.namespace = "";
            if (this.B2CRates != null) {
                info.setValue(this.B2CRates);
            }

        }
        if (index == 2) {
            info.name = "AgentMarkUp";
            info.namespace = "";
            if (this.AgentMarkUp != null) {
                info.setValue(this.AgentMarkUp);
            }

        }
        if (index == 3) {
            info.name = "Currency";
            info.namespace = "";
            if (this.Currency != null) {
                info.setValue(this.Currency);
            }

        }
        if (index == 4) {
            info.name = "RoomFare";
            info.namespace = "";
            if (this.RoomFare != null) {
                info.setValue(this.RoomFare);
            }

        }
        if (index == 5) {
            info.name = "RoomTax";
            info.namespace = "";
            if (this.RoomTax != null) {
                info.setValue(this.RoomTax);
            }

        }
        if (index == 6) {
            info.name = "PrefPrice";
            info.namespace = "";
            if (this.PrefPrice != null) {
                info.setValue(this.PrefPrice);
            }

        }
        if (index == 7) {
            info.name = "HeadGSAMarkUp";
            info.namespace = "";
            if (this.HeadGSAMarkUp != null) {
                info.setValue(this.HeadGSAMarkUp);
            }

        }
        if (index == 8) {
            info.name = "TotalFare";
            info.namespace = "";
            if (this.TotalFare != null) {
                info.setValue(this.TotalFare);
            }

        }
        if (index == 9) {
            info.name = "PrefCurrency";
            info.namespace = "";
            if (this.PrefCurrency != null) {
                info.setValue(this.PrefCurrency);
            }

        }
    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }    
}

