package com.Tamm.Hotels.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.5.5
//
// Created by Quasar Development 
//
//---------------------------------------------------


import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.AttributeInfo;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;

import java.math.BigDecimal;
import java.util.Hashtable;

public class SuppInfo extends AttributeContainer implements KvmSerializable {


    public Integer SuppID = 0;

    public Enums.SuppChargeType SuppChargeType = Enums.SuppChargeType.Included;

    public BigDecimal Price = BigDecimal.ZERO;

    public Boolean SuppIsSelected = false;
    private transient java.lang.Object __source;


    public void loadFromSoap(java.lang.Object paramObj, ExtendedSoapSerializationEnvelope __envelope) {
        if (paramObj == null)
            return;
        AttributeContainer inObj = (AttributeContainer) paramObj;
        __source = inObj;
        if (inObj instanceof SoapObject) {
            SoapObject soapObject = (SoapObject) inObj;
            int size = soapObject.getPropertyCount();
            for (int i0 = 0; i0 < size; i0++) {
                PropertyInfo info = soapObject.getPropertyInfo(i0);
                if (!loadProperty(info, soapObject, __envelope)) {
                }
            }
        }
        if (inObj.hasAttribute("SuppID")) {
            java.lang.Object j = inObj.getAttribute("SuppID");
            if (j != null) {
                SuppID = Integer.parseInt(j.toString());
            }
        }
        if (inObj.hasAttribute("SuppChargeType")) {
            java.lang.Object j = inObj.getAttribute("SuppChargeType");
            if (j != null) {
                SuppChargeType = Enums.SuppChargeType.fromString(j.toString());
            }
        }
        if (inObj.hasAttribute("Price")) {
            java.lang.Object j = inObj.getAttribute("Price");
            if (j != null) {
                Price = new BigDecimal(j.toString());
            }
        }
        if (inObj.hasAttribute("SuppIsSelected")) {
            java.lang.Object j = inObj.getAttribute("SuppIsSelected");
            if (j != null) {
                SuppIsSelected = new Boolean(j.toString());
            }
        }

    }


    protected boolean loadProperty(PropertyInfo info, SoapObject soapObject, ExtendedSoapSerializationEnvelope __envelope) {
        java.lang.Object obj = info.getValue();
        return false;
    }

    public java.lang.Object getOriginalXmlSource() {
        return __source;
    }


    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 0;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1) {
    }


    @Override
    public int getAttributeCount() {
        return 4;
    }

    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if (index == 0) {
            info.name = "SuppID";
            info.namespace = "";
            if (this.SuppID != null) {
                info.setValue(this.SuppID);
            }

        }
        if (index == 1) {
            info.name = "SuppChargeType";
            info.namespace = "";
            if (this.SuppChargeType != null) {
                info.setValue(this.SuppChargeType);
            }

        }
        if (index == 2) {
            info.name = "Price";
            info.namespace = "";
            if (this.Price != null) {
                info.setValue(this.Price);
            }

        }
        if (index == 3) {
            info.name = "SuppIsSelected";
            info.namespace = "";
            if (this.SuppIsSelected != null) {
                info.setValue(this.SuppIsSelected);
            }

        }
    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }
}

